sonar.projectKey=NPuhlmann_whiskyWanderungenApp_2dffbeb4-eedf-4757-9332-491ac157aa3e
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.freezed.dart,**/*.g.dart

# Written by the "Run critical tests with coverage" step in sonarqube.yml.
sonar.flutter.coverage.reportPath=coverage/lcov.info
sonar.flutter.tests.reportPath=tests.output
