// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/UI/checkout/checkout_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whisky_hikes/data/repositories/payment_repository.dart' as _i4;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i2;
import 'package:whisky_hikes/domain/models/basic_payment_result.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBasicOrder_0 extends _i1.SmartFake implements _i2.BasicOrder {
  _FakeBasicOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasicPaymentResult_1 extends _i1.SmartFake
    implements _i3.BasicPaymentResult {
  _FakeBasicPaymentResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i4.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BasicOrder> createOrder({
    required int? hikeId,
    required String? userId,
    required double? amount,
    required _i2.DeliveryType? deliveryType,
    Map<String, dynamic>? deliveryAddress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #hikeId: hikeId,
              #userId: userId,
              #amount: amount,
              #deliveryType: deliveryType,
              #deliveryAddress: deliveryAddress,
            }),
            returnValue: _i5.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #amount: amount,
                  #deliveryType: deliveryType,
                  #deliveryAddress: deliveryAddress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BasicOrder>);

  @override
  _i5.Future<_i3.BasicPaymentResult> processPayment({
    required _i2.BasicOrder? order,
    required String? paymentMethodId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [], {
              #order: order,
              #paymentMethodId: paymentMethodId,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i3.BasicPaymentResult>.value(
              _FakeBasicPaymentResult_1(
                this,
                Invocation.method(#processPayment, [], {
                  #order: order,
                  #paymentMethodId: paymentMethodId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.BasicPaymentResult>);

  @override
  _i5.Future<_i2.BasicOrder> getOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i5.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#getOrderById, [orderId]),
              ),
            ),
          )
          as _i5.Future<_i2.BasicOrder>);

  @override
  _i5.Future<List<_i2.BasicOrder>> getUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [userId]),
            returnValue: _i5.Future<List<_i2.BasicOrder>>.value(
              <_i2.BasicOrder>[],
            ),
          )
          as _i5.Future<List<_i2.BasicOrder>>);

  @override
  _i5.Future<_i2.BasicOrder> updateOrderStatus({
    required int? orderId,
    required _i2.OrderStatus? status,
    String? trackingNumber,
    DateTime? estimatedDelivery,
    String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [], {
              #orderId: orderId,
              #status: status,
              #trackingNumber: trackingNumber,
              #estimatedDelivery: estimatedDelivery,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i5.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#updateOrderStatus, [], {
                  #orderId: orderId,
                  #status: status,
                  #trackingNumber: trackingNumber,
                  #estimatedDelivery: estimatedDelivery,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BasicOrder>);
}
