// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/data/services/workflow/enhanced_order_workflow_with_commission_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;
import 'package:whisky_hikes/data/models/pagination_result.dart' as _i4;
import 'package:whisky_hikes/data/services/commission/commission_service.dart'
    as _i9;
import 'package:whisky_hikes/data/services/database/backend_api.dart' as _i11;
import 'package:whisky_hikes/data/services/notifications/supabase_notification_service.dart'
    as _i18;
import 'package:whisky_hikes/data/services/tracking/order_tracking_service.dart'
    as _i20;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i5;
import 'package:whisky_hikes/domain/models/commission.dart' as _i2;
import 'package:whisky_hikes/domain/models/delivery_address.dart' as _i17;
import 'package:whisky_hikes/domain/models/enhanced_order.dart' as _i7;
import 'package:whisky_hikes/domain/models/hike.dart' as _i14;
import 'package:whisky_hikes/domain/models/notification_model.dart' as _i19;
import 'package:whisky_hikes/domain/models/profile.dart' as _i13;
import 'package:whisky_hikes/domain/models/review.dart' as _i8;
import 'package:whisky_hikes/domain/models/tasting_set.dart' as _i6;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommission_0 extends _i1.SmartFake implements _i2.Commission {
  _FakeCommission_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_1 extends _i1.SmartFake
    implements _i3.SupabaseClient {
  _FakeSupabaseClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginationResult_2<T> extends _i1.SmartFake
    implements _i4.PaginationResult<T> {
  _FakePaginationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasicOrder_3 extends _i1.SmartFake implements _i5.BasicOrder {
  _FakeBasicOrder_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTastingSet_4 extends _i1.SmartFake implements _i6.TastingSet {
  _FakeTastingSet_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnhancedOrder_5 extends _i1.SmartFake implements _i7.EnhancedOrder {
  _FakeEnhancedOrder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReview_6 extends _i1.SmartFake implements _i8.Review {
  _FakeReview_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommissionService extends _i1.Mock implements _i9.CommissionService {
  MockCommissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Commission> createCommissionForOrder({
    required int? hikeId,
    required String? companyId,
    required String? orderId,
    required double? baseAmount,
    required double? commissionRate,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCommissionForOrder, [], {
              #hikeId: hikeId,
              #companyId: companyId,
              #orderId: orderId,
              #baseAmount: baseAmount,
              #commissionRate: commissionRate,
              #notes: notes,
            }),
            returnValue: _i10.Future<_i2.Commission>.value(
              _FakeCommission_0(
                this,
                Invocation.method(#createCommissionForOrder, [], {
                  #hikeId: hikeId,
                  #companyId: companyId,
                  #orderId: orderId,
                  #baseAmount: baseAmount,
                  #commissionRate: commissionRate,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.Commission>);

  @override
  _i10.Future<List<_i2.Commission>> getCommissionsForCompany(
    String? companyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionsForCompany, [companyId]),
            returnValue: _i10.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i10.Future<List<_i2.Commission>>);

  @override
  _i10.Future<List<_i2.Commission>> getCommissionsByStatus(
    String? companyId,
    _i2.CommissionStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionsByStatus, [companyId, status]),
            returnValue: _i10.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i10.Future<List<_i2.Commission>>);

  @override
  _i10.Future<_i2.Commission?> getCommissionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionById, [id]),
            returnValue: _i10.Future<_i2.Commission?>.value(),
          )
          as _i10.Future<_i2.Commission?>);

  @override
  _i10.Future<_i2.Commission?> getCommissionByOrderId(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionByOrderId, [orderId]),
            returnValue: _i10.Future<_i2.Commission?>.value(),
          )
          as _i10.Future<_i2.Commission?>);

  @override
  _i10.Future<_i2.Commission> markCommissionAsPaid(
    int? commissionId, {
    String? billingPeriodId,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markCommissionAsPaid,
              [commissionId],
              {#billingPeriodId: billingPeriodId, #notes: notes},
            ),
            returnValue: _i10.Future<_i2.Commission>.value(
              _FakeCommission_0(
                this,
                Invocation.method(
                  #markCommissionAsPaid,
                  [commissionId],
                  {#billingPeriodId: billingPeriodId, #notes: notes},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Commission>);

  @override
  _i10.Future<_i2.Commission> updateCommissionStatus(
    int? commissionId,
    _i2.CommissionStatus? status, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCommissionStatus,
              [commissionId, status],
              {#notes: notes},
            ),
            returnValue: _i10.Future<_i2.Commission>.value(
              _FakeCommission_0(
                this,
                Invocation.method(
                  #updateCommissionStatus,
                  [commissionId, status],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Commission>);

  @override
  _i10.Future<_i2.Commission> cancelCommission(
    int? commissionId, {
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelCommission,
              [commissionId],
              {#reason: reason},
            ),
            returnValue: _i10.Future<_i2.Commission>.value(
              _FakeCommission_0(
                this,
                Invocation.method(
                  #cancelCommission,
                  [commissionId],
                  {#reason: reason},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.Commission>);

  @override
  _i10.Future<Map<String, dynamic>> getCommissionStatistics(
    String? companyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionStatistics, [companyId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<_i2.Commission>> getCommissionsForDateRange(
    String? companyId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionsForDateRange, [
              companyId,
              startDate,
              endDate,
            ]),
            returnValue: _i10.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i10.Future<List<_i2.Commission>>);

  @override
  _i10.Future<List<_i2.Commission>> getOverdueCommissions(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueCommissions, [companyId]),
            returnValue: _i10.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i10.Future<List<_i2.Commission>>);

  @override
  _i10.Future<List<_i2.Commission>> processBatchPayment(
    List<int>? commissionIds, {
    String? billingPeriodId,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processBatchPayment,
              [commissionIds],
              {#billingPeriodId: billingPeriodId, #notes: notes},
            ),
            returnValue: _i10.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i10.Future<List<_i2.Commission>>);

  @override
  _i10.Future<double> getTotalCommissionForPeriod(String? billingPeriodId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCommissionForPeriod, [billingPeriodId]),
            returnValue: _i10.Future<double>.value(0.0),
          )
          as _i10.Future<double>);

  @override
  _i10.Future<Map<int, Map<String, dynamic>>> getCommissionSummaryByHike(
    String? companyId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCommissionSummaryByHike,
              [companyId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i10.Future<Map<int, Map<String, dynamic>>>.value(
              <int, Map<String, dynamic>>{},
            ),
          )
          as _i10.Future<Map<int, Map<String, dynamic>>>);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i11.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_1(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i3.SupabaseClient);

  @override
  String get supabaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseUrl),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#supabaseUrl),
            ),
          )
          as String);

  @override
  String get supabaseAnonKey =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseAnonKey),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#supabaseAnonKey),
            ),
          )
          as String);

  @override
  _i10.Future<_i13.Profile?> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i10.Future<_i13.Profile?>.value(),
          )
          as _i10.Future<_i13.Profile?>);

  @override
  _i10.Future<List<_i14.Hike>> fetchHikes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHikes, []),
            returnValue: _i10.Future<List<_i14.Hike>>.value(<_i14.Hike>[]),
          )
          as _i10.Future<List<_i14.Hike>>);

  @override
  _i10.Future<_i4.PaginationResult<_i14.Hike>> fetchHikesPaginated(
    _i4.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHikesPaginated, [params]),
            returnValue: _i10.Future<_i4.PaginationResult<_i14.Hike>>.value(
              _FakePaginationResult_2<_i14.Hike>(
                this,
                Invocation.method(#fetchHikesPaginated, [params]),
              ),
            ),
          )
          as _i10.Future<_i4.PaginationResult<_i14.Hike>>);

  @override
  _i10.Future<List<_i14.Hike>> fetchUserHikes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserHikes, [userId]),
            returnValue: _i10.Future<List<_i14.Hike>>.value(<_i14.Hike>[]),
          )
          as _i10.Future<List<_i14.Hike>>);

  @override
  _i10.Future<void> deleteHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHike, [hikeId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> uploadHikeImages(int? hikeId, List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hikeId, imageUrls]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateUserProfile(_i13.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> uploadProfileImage(
    String? userId,
    _i15.Uint8List? fileBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              fileBytes,
              fileExt,
            ]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  fileBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<List<_i16.Waypoint>> getWaypointsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getWaypointsForHike, [hikeId]),
            returnValue: _i10.Future<List<_i16.Waypoint>>.value(
              <_i16.Waypoint>[],
            ),
          )
          as _i10.Future<List<_i16.Waypoint>>);

  @override
  _i10.Future<void> addWaypoint(
    _i16.Waypoint? waypoint,
    int? hikeId, {
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addWaypoint,
              [waypoint, hikeId],
              {#orderIndex: orderIndex},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateWaypoint(_i16.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypoint, [waypoint]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteWaypoint(int? waypointId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWaypoint, [waypointId, hikeId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateWaypointOrder(
    int? hikeId,
    int? waypointId,
    int? newOrderIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypointOrder, [
              hikeId,
              waypointId,
              newOrderIndex,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i5.BasicOrder>> fetchUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserOrders, [userId]),
            returnValue: _i10.Future<List<_i5.BasicOrder>>.value(
              <_i5.BasicOrder>[],
            ),
          )
          as _i10.Future<List<_i5.BasicOrder>>);

  @override
  _i10.Future<_i5.BasicOrder> fetchOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i10.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_3(
                this,
                Invocation.method(#fetchOrderById, [orderId]),
              ),
            ),
          )
          as _i10.Future<_i5.BasicOrder>);

  @override
  _i10.Future<bool> hasUserPurchasedHike(String? userId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserPurchasedHike, [userId, hikeId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> recordHikePurchase(
    String? userId,
    int? hikeId,
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordHikePurchase, [userId, hikeId, orderId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i5.BasicOrder> fetchOrderWithPaymentDetails(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
            returnValue: _i10.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_3(
                this,
                Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
              ),
            ),
          )
          as _i10.Future<_i5.BasicOrder>);

  @override
  _i10.Future<_i5.BasicOrder> updateOrderAfterPayment({
    required int? orderId,
    required _i5.OrderStatus? status,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderAfterPayment, [], {
              #orderId: orderId,
              #status: status,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i10.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_3(
                this,
                Invocation.method(#updateOrderAfterPayment, [], {
                  #orderId: orderId,
                  #status: status,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.BasicOrder>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getUserPaymentHistory(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPaymentHistory, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<_i6.TastingSet?> getTastingSetForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetForHike, [hikeId]),
            returnValue: _i10.Future<_i6.TastingSet?>.value(),
          )
          as _i10.Future<_i6.TastingSet?>);

  @override
  _i10.Future<_i6.TastingSet?> getTastingSetById(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetById, [tastingSetId]),
            returnValue: _i10.Future<_i6.TastingSet?>.value(),
          )
          as _i10.Future<_i6.TastingSet?>);

  @override
  _i10.Future<List<_i6.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i10.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i10.Future<List<_i6.TastingSet>>);

  @override
  _i10.Future<List<_i6.WhiskySample>> getWhiskySamplesForTastingSet(
    int? tastingSetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWhiskySamplesForTastingSet, [tastingSetId]),
            returnValue: _i10.Future<List<_i6.WhiskySample>>.value(
              <_i6.WhiskySample>[],
            ),
          )
          as _i10.Future<List<_i6.WhiskySample>>);

  @override
  _i10.Future<List<_i6.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i10.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i10.Future<List<_i6.TastingSet>>);

  @override
  _i10.Future<List<_i6.TastingSet>> getTastingSetsByRegion(String? region) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsByRegion, [region]),
            returnValue: _i10.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i10.Future<List<_i6.TastingSet>>);

  @override
  _i10.Future<List<_i6.TastingSet>> getCurrentlyAvailableTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentlyAvailableTastingSets, []),
            returnValue: _i10.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i10.Future<List<_i6.TastingSet>>);

  @override
  _i10.Future<void> updateTastingSetAvailability(
    int? tastingSetId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSetAvailability, [
              tastingSetId,
              isAvailable,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.TastingSet>> getTastingSetsWithPagination({
    int? limit = 10,
    int? offset = 0,
    String? orderBy = 'created_at',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsWithPagination, [], {
              #limit: limit,
              #offset: offset,
              #orderBy: orderBy,
              #ascending: ascending,
            }),
            returnValue: _i10.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i10.Future<List<_i6.TastingSet>>);

  @override
  _i10.Future<_i6.TastingSet> createTastingSet({
    required int? hikeId,
    required String? name,
    required String? description,
    String? imageUrl,
    bool? isIncluded = true,
    bool? isAvailable = true,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [], {
              #hikeId: hikeId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i10.Future<_i6.TastingSet>.value(
              _FakeTastingSet_4(
                this,
                Invocation.method(#createTastingSet, [], {
                  #hikeId: hikeId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.TastingSet>);

  @override
  _i10.Future<_i6.TastingSet> updateTastingSet({
    required int? tastingSetId,
    String? name,
    String? description,
    String? imageUrl,
    bool? isIncluded,
    bool? isAvailable,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [], {
              #tastingSetId: tastingSetId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i10.Future<_i6.TastingSet>.value(
              _FakeTastingSet_4(
                this,
                Invocation.method(#updateTastingSet, [], {
                  #tastingSetId: tastingSetId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.TastingSet>);

  @override
  _i10.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.EnhancedOrder> createEnhancedOrderWithShipping({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? baseOrderValue,
    double? taxAmount = 0.0,
    String? currency = 'EUR',
    required _i17.DeliveryAddress? deliveryAddress,
    _i5.DeliveryType? deliveryType = _i5.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrderWithShipping, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #baseOrderValue: baseOrderValue,
              #taxAmount: taxAmount,
              #currency: currency,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#createEnhancedOrderWithShipping, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #baseOrderValue: baseOrderValue,
                  #taxAmount: taxAmount,
                  #currency: currency,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder> createEnhancedOrder({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? subtotal,
    double? taxAmount = 0.0,
    double? shippingCost = 0.0,
    required double? totalAmount,
    String? currency = 'EUR',
    double? baseAmount = 0.0,
    required _i17.DeliveryAddress? deliveryAddress,
    _i5.DeliveryType? deliveryType = _i5.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrder, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #subtotal: subtotal,
              #taxAmount: taxAmount,
              #shippingCost: shippingCost,
              #totalAmount: totalAmount,
              #currency: currency,
              #baseAmount: baseAmount,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#createEnhancedOrder, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #subtotal: subtotal,
                  #taxAmount: taxAmount,
                  #shippingCost: shippingCost,
                  #totalAmount: totalAmount,
                  #currency: currency,
                  #baseAmount: baseAmount,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder?> getEnhancedOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedOrderById, [orderId]),
            returnValue: _i10.Future<_i7.EnhancedOrder?>.value(),
          )
          as _i10.Future<_i7.EnhancedOrder?>);

  @override
  _i10.Future<_i7.EnhancedOrder?> getEnhancedOrderByNumber(
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedOrderByNumber, [orderNumber]),
            returnValue: _i10.Future<_i7.EnhancedOrder?>.value(),
          )
          as _i10.Future<_i7.EnhancedOrder?>);

  @override
  _i10.Future<List<_i7.EnhancedOrder>> getCustomerEnhancedOrders({
    required String? customerId,
    int? limit = 50,
    int? offset = 0,
    List<String>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerEnhancedOrders, [], {
              #customerId: customerId,
              #limit: limit,
              #offset: offset,
              #statuses: statuses,
            }),
            returnValue: _i10.Future<List<_i7.EnhancedOrder>>.value(
              <_i7.EnhancedOrder>[],
            ),
          )
          as _i10.Future<List<_i7.EnhancedOrder>>);

  @override
  _i10.Future<List<_i7.EnhancedOrder>> getCompanyEnhancedOrders({
    required String? companyId,
    int? limit = 100,
    int? offset = 0,
    List<String>? statuses,
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyEnhancedOrders, [], {
              #companyId: companyId,
              #limit: limit,
              #offset: offset,
              #statuses: statuses,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i10.Future<List<_i7.EnhancedOrder>>.value(
              <_i7.EnhancedOrder>[],
            ),
          )
          as _i10.Future<List<_i7.EnhancedOrder>>);

  @override
  _i10.Future<_i7.EnhancedOrder> updateEnhancedOrderStatus({
    required int? orderId,
    required String? newStatus,
    String? reason,
    String? notes,
    String? trackingNumber,
    String? trackingUrl,
    String? shippingCarrier,
    DateTime? estimatedDelivery,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEnhancedOrderStatus, [], {
              #orderId: orderId,
              #newStatus: newStatus,
              #reason: reason,
              #notes: notes,
              #trackingNumber: trackingNumber,
              #trackingUrl: trackingUrl,
              #shippingCarrier: shippingCarrier,
              #estimatedDelivery: estimatedDelivery,
              #metadata: metadata,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#updateEnhancedOrderStatus, [], {
                  #orderId: orderId,
                  #newStatus: newStatus,
                  #reason: reason,
                  #notes: notes,
                  #trackingNumber: trackingNumber,
                  #trackingUrl: trackingUrl,
                  #shippingCarrier: shippingCarrier,
                  #estimatedDelivery: estimatedDelivery,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder> addTrackingToEnhancedOrder({
    required int? orderId,
    required String? trackingNumber,
    String? shippingCarrier,
    String? shippingService,
    DateTime? estimatedDelivery,
    String? trackingUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackingToEnhancedOrder, [], {
              #orderId: orderId,
              #trackingNumber: trackingNumber,
              #shippingCarrier: shippingCarrier,
              #shippingService: shippingService,
              #estimatedDelivery: estimatedDelivery,
              #trackingUrl: trackingUrl,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#addTrackingToEnhancedOrder, [], {
                  #orderId: orderId,
                  #trackingNumber: trackingNumber,
                  #shippingCarrier: shippingCarrier,
                  #shippingService: shippingService,
                  #estimatedDelivery: estimatedDelivery,
                  #trackingUrl: trackingUrl,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<List<_i7.OrderStatusChange>> getOrderStatusHistory(
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusHistory, [orderId]),
            returnValue: _i10.Future<List<_i7.OrderStatusChange>>.value(
              <_i7.OrderStatusChange>[],
            ),
          )
          as _i10.Future<List<_i7.OrderStatusChange>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getShippingCarriers() =>
      (super.noSuchMethod(
            Invocation.method(#getShippingCarriers, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getShippingMethods(
    String? carrierCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getShippingMethods, [carrierCode]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<_i7.EnhancedOrder> convertBasicToEnhancedOrder({
    required _i5.BasicOrder? basicOrder,
    required String? companyId,
    required _i17.DeliveryAddress? deliveryAddress,
    String? customerEmail,
    String? customerPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertBasicToEnhancedOrder, [], {
              #basicOrder: basicOrder,
              #companyId: companyId,
              #deliveryAddress: deliveryAddress,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#convertBasicToEnhancedOrder, [], {
                  #basicOrder: basicOrder,
                  #companyId: companyId,
                  #deliveryAddress: deliveryAddress,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<List<_i8.Review>> getReviewsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForHike, [hikeId]),
            returnValue: _i10.Future<List<_i8.Review>>.value(<_i8.Review>[]),
          )
          as _i10.Future<List<_i8.Review>>);

  @override
  _i10.Future<_i8.Review> createReview({
    required int? hikeId,
    required String? userId,
    required double? rating,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [], {
              #hikeId: hikeId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i10.Future<_i8.Review>.value(
              _FakeReview_6(
                this,
                Invocation.method(#createReview, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i10.Future<_i8.Review>);

  @override
  _i10.Future<_i8.Review> updateReview({
    required int? reviewId,
    required String? userId,
    double? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [], {
              #reviewId: reviewId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i10.Future<_i8.Review>.value(
              _FakeReview_6(
                this,
                Invocation.method(#updateReview, [], {
                  #reviewId: reviewId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i10.Future<_i8.Review>);

  @override
  _i10.Future<void> deleteReview({
    required int? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [], {
              #reviewId: reviewId,
              #userId: userId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i8.Review>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByUser, [userId]),
            returnValue: _i10.Future<List<_i8.Review>>.value(<_i8.Review>[]),
          )
          as _i10.Future<List<_i8.Review>>);

  @override
  _i10.Future<double> getAverageRatingForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getAverageRatingForHike, [hikeId]),
            returnValue: _i10.Future<double>.value(0.0),
          )
          as _i10.Future<double>);

  @override
  _i10.Future<_i8.Review?> getUserReviewForHike({
    required int? hikeId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReviewForHike, [], {
              #hikeId: hikeId,
              #userId: userId,
            }),
            returnValue: _i10.Future<_i8.Review?>.value(),
          )
          as _i10.Future<_i8.Review?>);

  @override
  _i10.Future<Map<String, dynamic>> getReviewStatsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewStatsForHike, [hikeId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<_i8.Review>> getRecentReviews({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentReviews, [], {#limit: limit}),
            returnValue: _i10.Future<List<_i8.Review>>.value(<_i8.Review>[]),
          )
          as _i10.Future<List<_i8.Review>>);
}

/// A class which mocks [SupabaseNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseNotificationService extends _i1.Mock
    implements _i18.SupabaseNotificationService {
  MockSupabaseNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToOrderUpdates() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToOrderUpdates, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> showNotification({
    required String? title,
    required String? body,
    String? payload,
    _i19.NotificationType? type = _i19.NotificationType.general,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #title: title,
              #body: body,
              #payload: payload,
              #type: type,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i19.NotificationModel>> getUserNotifications(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserNotifications, [userId]),
            returnValue: _i10.Future<List<_i19.NotificationModel>>.value(
              <_i19.NotificationModel>[],
            ),
          )
          as _i10.Future<List<_i19.NotificationModel>>);

  @override
  _i10.Future<bool> markNotificationAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [notificationId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<int> getUnreadNotificationCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationCount, [userId]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<bool> markAllNotificationsAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsAsRead, [userId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> clearAllNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllNotifications, [userId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> sendOrderTrackingNotification({
    required String? customerId,
    required int? orderId,
    required String? orderNumber,
    required String? trackingNumber,
    required String? shippingCarrier,
    DateTime? estimatedDelivery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOrderTrackingNotification, [], {
              #customerId: customerId,
              #orderId: orderId,
              #orderNumber: orderNumber,
              #trackingNumber: trackingNumber,
              #shippingCarrier: shippingCarrier,
              #estimatedDelivery: estimatedDelivery,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendOrderStatusChangeNotification({
    required String? customerId,
    required int? orderId,
    required String? orderNumber,
    required String? newStatus,
    String? statusDescription,
    String? trackingNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOrderStatusChangeNotification, [], {
              #customerId: customerId,
              #orderId: orderId,
              #orderNumber: orderNumber,
              #newStatus: newStatus,
              #statusDescription: statusDescription,
              #trackingNumber: trackingNumber,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendOrderOutForDeliveryNotification({
    required String? customerId,
    required int? orderId,
    required String? orderNumber,
    DateTime? estimatedDeliveryTime,
    String? courierName,
    String? courierPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOrderOutForDeliveryNotification, [], {
              #customerId: customerId,
              #orderId: orderId,
              #orderNumber: orderNumber,
              #estimatedDeliveryTime: estimatedDeliveryTime,
              #courierName: courierName,
              #courierPhone: courierPhone,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendOrderDeliveredNotification({
    required String? customerId,
    required int? orderId,
    required String? orderNumber,
    required DateTime? deliveryTime,
    String? recipientName,
    String? deliveryProofUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOrderDeliveredNotification, [], {
              #customerId: customerId,
              #orderId: orderId,
              #orderNumber: orderNumber,
              #deliveryTime: deliveryTime,
              #recipientName: recipientName,
              #deliveryProofUrl: deliveryProofUrl,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToEnhancedOrderUpdates() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToEnhancedOrderUpdates, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [OrderTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingService extends _i1.Mock
    implements _i20.OrderTrackingService {
  MockOrderTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i7.EnhancedOrder> assignTrackingNumber({
    required int? orderId,
    required String? trackingNumber,
    required String? shippingCarrier,
    String? shippingService,
    DateTime? estimatedDelivery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assignTrackingNumber, [], {
              #orderId: orderId,
              #trackingNumber: trackingNumber,
              #shippingCarrier: shippingCarrier,
              #shippingService: shippingService,
              #estimatedDelivery: estimatedDelivery,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#assignTrackingNumber, [], {
                  #orderId: orderId,
                  #trackingNumber: trackingNumber,
                  #shippingCarrier: shippingCarrier,
                  #shippingService: shippingService,
                  #estimatedDelivery: estimatedDelivery,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder> updateTrackingStatus({
    required String? trackingNumber,
    required String? newStatus,
    String? statusDescription,
    String? location,
    DateTime? timestamp,
    Map<String, dynamic>? carrierData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrackingStatus, [], {
              #trackingNumber: trackingNumber,
              #newStatus: newStatus,
              #statusDescription: statusDescription,
              #location: location,
              #timestamp: timestamp,
              #carrierData: carrierData,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#updateTrackingStatus, [], {
                  #trackingNumber: trackingNumber,
                  #newStatus: newStatus,
                  #statusDescription: statusDescription,
                  #location: location,
                  #timestamp: timestamp,
                  #carrierData: carrierData,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder> markOutForDelivery({
    required int? orderId,
    DateTime? estimatedDeliveryTime,
    String? deliveryInstructions,
    String? courierName,
    String? courierPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markOutForDelivery, [], {
              #orderId: orderId,
              #estimatedDeliveryTime: estimatedDeliveryTime,
              #deliveryInstructions: deliveryInstructions,
              #courierName: courierName,
              #courierPhone: courierPhone,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#markOutForDelivery, [], {
                  #orderId: orderId,
                  #estimatedDeliveryTime: estimatedDeliveryTime,
                  #deliveryInstructions: deliveryInstructions,
                  #courierName: courierName,
                  #courierPhone: courierPhone,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<_i7.EnhancedOrder> markDelivered({
    required int? orderId,
    DateTime? deliveryTime,
    String? deliveryLocation,
    String? recipientName,
    String? deliveryProofUrl,
    String? deliveryNotes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markDelivered, [], {
              #orderId: orderId,
              #deliveryTime: deliveryTime,
              #deliveryLocation: deliveryLocation,
              #recipientName: recipientName,
              #deliveryProofUrl: deliveryProofUrl,
              #deliveryNotes: deliveryNotes,
            }),
            returnValue: _i10.Future<_i7.EnhancedOrder>.value(
              _FakeEnhancedOrder_5(
                this,
                Invocation.method(#markDelivered, [], {
                  #orderId: orderId,
                  #deliveryTime: deliveryTime,
                  #deliveryLocation: deliveryLocation,
                  #recipientName: recipientName,
                  #deliveryProofUrl: deliveryProofUrl,
                  #deliveryNotes: deliveryNotes,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.EnhancedOrder>);

  @override
  _i10.Future<Map<String, dynamic>> getTrackingInformation(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackingInformation, [orderId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Stream<Map<String, dynamic>> trackOrderRealTime(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#trackOrderRealTime, [orderId]),
            returnValue: _i10.Stream<Map<String, dynamic>>.empty(),
          )
          as _i10.Stream<Map<String, dynamic>>);

  @override
  _i10.Future<void> batchUpdateTrackingStatus(
    List<Map<String, dynamic>>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateTrackingStatus, [updates]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
