// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/UI/navigation/navigation_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:geolocator/geolocator.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:whisky_hikes/data/services/location/location_service.dart'
    as _i2;
import 'package:whisky_hikes/data/services/navigation/navigation_service.dart'
    as _i7;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i2.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Position> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i3.Stream<_i4.Position>.empty(),
          )
          as _i3.Stream<_i4.Position>);

  @override
  bool get isTracking =>
      (super.noSuchMethod(Invocation.getter(#isTracking), returnValue: false)
          as bool);

  @override
  _i3.Future<bool> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> startTracking() =>
      (super.noSuchMethod(
            Invocation.method(#startTracking, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> stopTracking() =>
      (super.noSuchMethod(
            Invocation.method(#stopTracking, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  double? calculateDistanceToWaypoint(_i5.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistanceToWaypoint, [waypoint]),
          )
          as double?);

  @override
  double? calculateBearingToWaypoint(_i5.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#calculateBearingToWaypoint, [waypoint]),
          )
          as double?);

  @override
  bool isWaypointReached(_i5.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#isWaypointReached, [waypoint]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Waypoint? findNearestWaypoint(List<_i5.Waypoint>? waypoints) =>
      (super.noSuchMethod(Invocation.method(#findNearestWaypoint, [waypoints]))
          as _i5.Waypoint?);

  @override
  Duration? calculateEstimatedTimeToWaypoint(_i5.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#calculateEstimatedTimeToWaypoint, [waypoint]),
          )
          as Duration?);

  @override
  String bearingToDirectionText(double? bearing) =>
      (super.noSuchMethod(
            Invocation.method(#bearingToDirectionText, [bearing]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#bearingToDirectionText, [bearing]),
            ),
          )
          as String);

  @override
  String formatDistance(double? distanceInMeters) =>
      (super.noSuchMethod(
            Invocation.method(#formatDistance, [distanceInMeters]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#formatDistance, [distanceInMeters]),
            ),
          )
          as String);

  @override
  String formatDuration(Duration? duration) =>
      (super.noSuchMethod(
            Invocation.method(#formatDuration, [duration]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#formatDuration, [duration]),
            ),
          )
          as String);

  @override
  _i3.Future<void> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<_i4.Position?>.value(),
          )
          as _i3.Future<_i4.Position?>);

  @override
  _i3.Future<bool> isBackgroundLocationEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBackgroundLocationEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestBackgroundLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestBackgroundLocationPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i7.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Waypoint> get waypoints =>
      (super.noSuchMethod(
            Invocation.getter(#waypoints),
            returnValue: <_i5.Waypoint>[],
          )
          as List<_i5.Waypoint>);

  @override
  int get currentWaypointIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentWaypointIndex),
            returnValue: 0,
          )
          as int);

  @override
  _i7.NavigationStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i7.NavigationStatus.idle,
          )
          as _i7.NavigationStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<bool> startNavigation(List<_i5.Waypoint>? waypoints) =>
      (super.noSuchMethod(
            Invocation.method(#startNavigation, [waypoints]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> pauseNavigation() =>
      (super.noSuchMethod(
            Invocation.method(#pauseNavigation, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resumeNavigation() =>
      (super.noSuchMethod(
            Invocation.method(#resumeNavigation, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopNavigation() =>
      (super.noSuchMethod(
            Invocation.method(#stopNavigation, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> skipToNextWaypoint() =>
      (super.noSuchMethod(
            Invocation.method(#skipToNextWaypoint, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> skipToPreviousWaypoint() =>
      (super.noSuchMethod(
            Invocation.method(#skipToPreviousWaypoint, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  Map<String, dynamic> getNavigationStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getNavigationStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> checkNavigationPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkNavigationPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestNavigationPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestNavigationPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
