// Mocks generated by Mockito 5.4.4 from annotations
// in whisky_hikes/test/data/repositories/review_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whisky_hikes/data/services/database/backend_api.dart' as _i2;
import 'package:whisky_hikes/domain/models/review.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i2.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Review>> getReviewsForHike(int? hikeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewsForHike,
          [hikeId],
        ),
        returnValue: _i3.Future<List<_i4.Review>>.value(<_i4.Review>[]),
      ) as _i3.Future<List<_i4.Review>>);

  @override
  _i3.Future<_i4.Review> createReview({
    required int? hikeId,
    required String? userId,
    required double? rating,
    required String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReview,
          [],
          {
            #hikeId: hikeId,
            #userId: userId,
            #rating: rating,
            #comment: comment,
          },
        ),
        returnValue: _i3.Future<_i4.Review>.value(_FakeReview_0(this, Invocation.method(#createReview, []))),
      ) as _i3.Future<_i4.Review>);

  @override
  _i3.Future<_i4.Review> updateReview({
    required int? reviewId,
    required String? userId,
    double? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReview,
          [],
          {
            #reviewId: reviewId,
            #userId: userId,
            #rating: rating,
            #comment: comment,
          },
        ),
        returnValue: _i3.Future<_i4.Review>.value(_FakeReview_0(this, Invocation.method(#createReview, []))),
      ) as _i3.Future<_i4.Review>);

  @override
  _i3.Future<void> deleteReview({
    required int? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReview,
          [],
          {
            #reviewId: reviewId,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Review>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewsByUser,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.Review>>.value(<_i4.Review>[]),
      ) as _i3.Future<List<_i4.Review>>);

  @override
  _i3.Future<double> getAverageRatingForHike(int? hikeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageRatingForHike,
          [hikeId],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<_i4.Review?> getUserReviewForHike({
    required int? hikeId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserReviewForHike,
          [],
          {
            #hikeId: hikeId,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<_i4.Review?>.value(),
      ) as _i3.Future<_i4.Review?>);

  @override
  _i3.Future<Map<String, dynamic>> getReviewStatsForHike(int? hikeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewStatsForHike,
          [hikeId],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.Review>> getRecentReviews({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentReviews,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Review>>.value(<_i4.Review>[]),
      ) as _i3.Future<List<_i4.Review>>);
}

/// A class which mocks [Review].
///
/// See the documentation for Mockito's code generation for more information.
class _FakeReview_0 extends _i1.SmartFake implements _i4.Review {
  _FakeReview_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}