// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/data/providers/commission_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whisky_hikes/data/repositories/commission_repository.dart'
    as _i3;
import 'package:whisky_hikes/domain/models/commission.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommission_0 extends _i1.SmartFake implements _i2.Commission {
  _FakeCommission_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommissionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommissionRepository extends _i1.Mock
    implements _i3.CommissionRepository {
  MockCommissionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Commission>> getCommissionsForCompany(
    String? companyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionsForCompany, [companyId]),
            returnValue: _i4.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i4.Future<List<_i2.Commission>>);

  @override
  _i4.Future<_i2.Commission?> getCommissionByOrderId(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionByOrderId, [orderId]),
            returnValue: _i4.Future<_i2.Commission?>.value(),
          )
          as _i4.Future<_i2.Commission?>);

  @override
  _i4.Future<List<_i2.Commission>> getCommissionsForDateRange(
    String? companyId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionsForDateRange, [
              companyId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i4.Future<List<_i2.Commission>>);

  @override
  _i4.Future<List<_i2.Commission>> getOverdueCommissions(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueCommissions, [companyId]),
            returnValue: _i4.Future<List<_i2.Commission>>.value(
              <_i2.Commission>[],
            ),
          )
          as _i4.Future<List<_i2.Commission>>);

  @override
  _i4.Future<Map<String, dynamic>> getCommissionStatistics(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommissionStatistics, [companyId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<int, Map<String, dynamic>>> getCommissionSummaryByHike(
    String? companyId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCommissionSummaryByHike,
              [companyId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i4.Future<Map<int, Map<String, dynamic>>>.value(
              <int, Map<String, dynamic>>{},
            ),
          )
          as _i4.Future<Map<int, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Commission> updateCommissionStatus(
    int? commissionId,
    _i2.CommissionStatus? status, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCommissionStatus,
              [commissionId, status],
              {#notes: notes},
            ),
            returnValue: _i4.Future<_i2.Commission>.value(
              _FakeCommission_0(
                this,
                Invocation.method(
                  #updateCommissionStatus,
                  [commissionId, status],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Commission>);
}
