// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/data/providers/dashboard_provider_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:whisky_hikes/data/services/admin/dashboard_metrics_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DashboardMetricsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardMetricsService extends _i1.Mock
    implements _i2.DashboardMetricsService {
  MockDashboardMetricsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getDailyRevenue() =>
      (super.noSuchMethod(
            Invocation.method(#getDailyRevenue, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<double> getWeeklyRevenue() =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyRevenue, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<double> getMonthlyRevenue() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyRevenue, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> getActiveOrdersByStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrdersByStatus, [status]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalActiveOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalActiveOrders, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getRecentOrders({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentOrders, [], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> getSoldRoutesToday() =>
      (super.noSuchMethod(
            Invocation.method(#getSoldRoutesToday, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getSoldRoutesThisWeek() =>
      (super.noSuchMethod(
            Invocation.method(#getSoldRoutesThisWeek, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getSoldRoutesThisMonth() =>
      (super.noSuchMethod(
            Invocation.method(#getSoldRoutesThisMonth, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMostPopularRoutes({
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMostPopularRoutes, [], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<double> getAverageCustomerRating() =>
      (super.noSuchMethod(
            Invocation.method(#getAverageCustomerRating, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<Map<String, dynamic>> getDashboardMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardMetrics, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  String formatCurrency(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#formatCurrency, [amount]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#formatCurrency, [amount]),
            ),
          )
          as String);

  @override
  String formatPercentage(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#formatPercentage, [value]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#formatPercentage, [value]),
            ),
          )
          as String);

  @override
  String formatNumber(int? number) =>
      (super.noSuchMethod(
            Invocation.method(#formatNumber, [number]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#formatNumber, [number]),
            ),
          )
          as String);
}
