// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/data/providers/order_management_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whisky_hikes/data/services/admin/order_management_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderManagementService extends _i1.Mock
    implements _i2.OrderManagementService {
  MockOrderManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllOrdersForAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrdersForAdmin, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> createOrder(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [orderData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateOrder(
    int? orderId,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [orderId, updateData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteOrder(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [orderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> updateOrderStatus(
    int? orderId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [orderId, newStatus]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getOrdersByStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersByStatus, [status]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchOrders(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchOrders, [searchTerm]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getOrdersByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersByDateRange, [startDate, endDate]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getOrdersByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersByUser, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getOrderStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatistics, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getRecentOrders({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentOrders, [], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  bool validateOrderData(Map<String, dynamic>? orderData) =>
      (super.noSuchMethod(
            Invocation.method(#validateOrderData, [orderData]),
            returnValue: false,
          )
          as bool);

  @override
  bool validateUpdateData(Map<String, dynamic>? updateData) =>
      (super.noSuchMethod(
            Invocation.method(#validateUpdateData, [updateData]),
            returnValue: false,
          )
          as bool);

  @override
  bool validateOrderStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#validateOrderStatus, [status]),
            returnValue: false,
          )
          as bool);

  @override
  List<String> getValidStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#getValidStatuses, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool isCompletedStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#isCompletedStatus, [status]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPendingStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#isPendingStatus, [status]),
            returnValue: false,
          )
          as bool);

  @override
  bool isCancelledStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#isCancelledStatus, [status]),
            returnValue: false,
          )
          as bool);
}
