// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/UI/orders/order_tracking_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:whisky_hikes/data/repositories/payment_repository.dart' as _i4;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i2;
import 'package:whisky_hikes/domain/models/delivery_address.dart' as _i7;
import 'package:whisky_hikes/domain/models/enhanced_order.dart' as _i3;
import 'package:whisky_hikes/domain/models/payment_intent.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBasicOrder_0 extends _i1.SmartFake implements _i2.BasicOrder {
  _FakeBasicOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnhancedOrder_1 extends _i1.SmartFake implements _i3.EnhancedOrder {
  _FakeEnhancedOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i4.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.PaymentMethodType>> getAvailablePaymentMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePaymentMethods, []),
            returnValue: _i5.Future<List<_i6.PaymentMethodType>>.value(
              <_i6.PaymentMethodType>[],
            ),
          )
          as _i5.Future<List<_i6.PaymentMethodType>>);

  @override
  _i5.Future<bool> isPaymentMethodAvailable(
    _i6.PaymentMethodType? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isPaymentMethodAvailable, [paymentMethod]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.BasicOrder> getOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i5.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#getOrderById, [orderId]),
              ),
            ),
          )
          as _i5.Future<_i2.BasicOrder>);

  @override
  _i5.Future<List<_i2.BasicOrder>> getUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [userId]),
            returnValue: _i5.Future<List<_i2.BasicOrder>>.value(
              <_i2.BasicOrder>[],
            ),
          )
          as _i5.Future<List<_i2.BasicOrder>>);

  @override
  _i5.Future<_i2.BasicOrder> updateOrderStatus({
    required int? orderId,
    required _i2.OrderStatus? status,
    String? trackingNumber,
    DateTime? estimatedDelivery,
    String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [], {
              #orderId: orderId,
              #status: status,
              #trackingNumber: trackingNumber,
              #estimatedDelivery: estimatedDelivery,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i5.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#updateOrderStatus, [], {
                  #orderId: orderId,
                  #status: status,
                  #trackingNumber: trackingNumber,
                  #estimatedDelivery: estimatedDelivery,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BasicOrder>);

  @override
  _i5.Future<_i3.EnhancedOrder> createEnhancedOrder({
    required int? hikeId,
    required String? userId,
    required String? companyId,
    required double? baseAmount,
    required _i7.DeliveryAddress? deliveryAddress,
    _i2.DeliveryType? deliveryType = _i2.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrder, [], {
              #hikeId: hikeId,
              #userId: userId,
              #companyId: companyId,
              #baseAmount: baseAmount,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i3.EnhancedOrder>.value(
              _FakeEnhancedOrder_1(
                this,
                Invocation.method(#createEnhancedOrder, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #companyId: companyId,
                  #baseAmount: baseAmount,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.EnhancedOrder>);

  @override
  _i5.Future<_i3.EnhancedOrder?> getEnhancedOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedOrderById, [orderId]),
            returnValue: _i5.Future<_i3.EnhancedOrder?>.value(),
          )
          as _i5.Future<_i3.EnhancedOrder?>);

  @override
  _i5.Future<List<_i3.EnhancedOrder>> getCustomerEnhancedOrders({
    required String? customerId,
    int? limit = 50,
    int? offset = 0,
    List<String>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerEnhancedOrders, [], {
              #customerId: customerId,
              #limit: limit,
              #offset: offset,
              #statuses: statuses,
            }),
            returnValue: _i5.Future<List<_i3.EnhancedOrder>>.value(
              <_i3.EnhancedOrder>[],
            ),
          )
          as _i5.Future<List<_i3.EnhancedOrder>>);

  @override
  _i5.Future<_i3.EnhancedOrder> updateEnhancedOrderStatus({
    required int? orderId,
    required String? newStatus,
    String? reason,
    String? trackingNumber,
    DateTime? estimatedDelivery,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEnhancedOrderStatus, [], {
              #orderId: orderId,
              #newStatus: newStatus,
              #reason: reason,
              #trackingNumber: trackingNumber,
              #estimatedDelivery: estimatedDelivery,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i3.EnhancedOrder>.value(
              _FakeEnhancedOrder_1(
                this,
                Invocation.method(#updateEnhancedOrderStatus, [], {
                  #orderId: orderId,
                  #newStatus: newStatus,
                  #reason: reason,
                  #trackingNumber: trackingNumber,
                  #estimatedDelivery: estimatedDelivery,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.EnhancedOrder>);

  @override
  _i5.Future<_i3.EnhancedOrder> convertToEnhancedOrder({
    required _i2.BasicOrder? basicOrder,
    required String? companyId,
    required _i7.DeliveryAddress? deliveryAddress,
    String? customerEmail,
    String? customerPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertToEnhancedOrder, [], {
              #basicOrder: basicOrder,
              #companyId: companyId,
              #deliveryAddress: deliveryAddress,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
            }),
            returnValue: _i5.Future<_i3.EnhancedOrder>.value(
              _FakeEnhancedOrder_1(
                this,
                Invocation.method(#convertToEnhancedOrder, [], {
                  #basicOrder: basicOrder,
                  #companyId: companyId,
                  #deliveryAddress: deliveryAddress,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.EnhancedOrder>);
}
