// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/mocks/mock_backend_api_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:whisky_hikes/data/services/database/backend_api.dart' as _i7;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i3;
import 'package:whisky_hikes/domain/models/delivery_address.dart' as _i14;
import 'package:whisky_hikes/domain/models/enhanced_order.dart' as _i5;
import 'package:whisky_hikes/domain/models/hike.dart' as _i11;
import 'package:whisky_hikes/domain/models/profile.dart' as _i10;
import 'package:whisky_hikes/domain/models/review.dart' as _i6;
import 'package:whisky_hikes/domain/models/tasting_set.dart' as _i4;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasicOrder_1 extends _i1.SmartFake implements _i3.BasicOrder {
  _FakeBasicOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTastingSet_2 extends _i1.SmartFake implements _i4.TastingSet {
  _FakeTastingSet_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnhancedOrder_3 extends _i1.SmartFake implements _i5.EnhancedOrder {
  _FakeEnhancedOrder_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReview_4 extends _i1.SmartFake implements _i6.Review {
  _FakeReview_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i7.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.SupabaseClient);

  @override
  String get supabaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#supabaseUrl),
            ),
          )
          as String);

  @override
  String get supabaseAnonKey =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseAnonKey),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#supabaseAnonKey),
            ),
          )
          as String);

  @override
  _i9.Future<_i10.Profile?> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i9.Future<_i10.Profile?>.value(),
          )
          as _i9.Future<_i10.Profile?>);

  @override
  _i9.Future<List<_i11.Hike>> fetchHikes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHikes, []),
            returnValue: _i9.Future<List<_i11.Hike>>.value(<_i11.Hike>[]),
          )
          as _i9.Future<List<_i11.Hike>>);

  @override
  _i9.Future<List<_i11.Hike>> fetchUserHikes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserHikes, [userId]),
            returnValue: _i9.Future<List<_i11.Hike>>.value(<_i11.Hike>[]),
          )
          as _i9.Future<List<_i11.Hike>>);

  @override
  _i9.Future<void> deleteHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHike, [hikeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> uploadHikeImages(int? hikeId, List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hikeId, imageUrls]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserProfile(_i10.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> uploadProfileImage(
    String? userId,
    _i12.Uint8List? fileBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              fileBytes,
              fileExt,
            ]),
            returnValue: _i9.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  fileBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<List<_i13.Waypoint>> getWaypointsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getWaypointsForHike, [hikeId]),
            returnValue: _i9.Future<List<_i13.Waypoint>>.value(
              <_i13.Waypoint>[],
            ),
          )
          as _i9.Future<List<_i13.Waypoint>>);

  @override
  _i9.Future<void> addWaypoint(
    _i13.Waypoint? waypoint,
    int? hikeId, {
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addWaypoint,
              [waypoint, hikeId],
              {#orderIndex: orderIndex},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateWaypoint(_i13.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypoint, [waypoint]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateWaypointOrder(
    int? hikeId,
    int? waypointId,
    int? newOrderIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypointOrder, [
              hikeId,
              waypointId,
              newOrderIndex,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.BasicOrder>> fetchUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserOrders, [userId]),
            returnValue: _i9.Future<List<_i3.BasicOrder>>.value(
              <_i3.BasicOrder>[],
            ),
          )
          as _i9.Future<List<_i3.BasicOrder>>);

  @override
  _i9.Future<_i3.BasicOrder> fetchOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i9.Future<_i3.BasicOrder>.value(
              _FakeBasicOrder_1(
                this,
                Invocation.method(#fetchOrderById, [orderId]),
              ),
            ),
          )
          as _i9.Future<_i3.BasicOrder>);

  @override
  _i9.Future<bool> hasUserPurchasedHike(String? userId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserPurchasedHike, [userId, hikeId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> recordHikePurchase(
    String? userId,
    int? hikeId,
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordHikePurchase, [userId, hikeId, orderId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.BasicOrder> fetchOrderWithPaymentDetails(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
            returnValue: _i9.Future<_i3.BasicOrder>.value(
              _FakeBasicOrder_1(
                this,
                Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
              ),
            ),
          )
          as _i9.Future<_i3.BasicOrder>);

  @override
  _i9.Future<_i3.BasicOrder> updateOrderAfterPayment({
    required int? orderId,
    required _i3.OrderStatus? status,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderAfterPayment, [], {
              #orderId: orderId,
              #status: status,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i9.Future<_i3.BasicOrder>.value(
              _FakeBasicOrder_1(
                this,
                Invocation.method(#updateOrderAfterPayment, [], {
                  #orderId: orderId,
                  #status: status,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.BasicOrder>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getUserPaymentHistory(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPaymentHistory, [userId]),
            returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<List<_i4.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<List<_i4.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<_i4.TastingSet> createTastingSet({
    required int? hikeId,
    required String? name,
    required String? description,
    String? imageUrl,
    bool? isIncluded = true,
    bool? isAvailable = true,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [], {
              #hikeId: hikeId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#createTastingSet, [], {
                  #hikeId: hikeId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<_i4.TastingSet> updateTastingSet({
    required int? tastingSetId,
    String? name,
    String? description,
    String? imageUrl,
    bool? isIncluded,
    bool? isAvailable,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [], {
              #tastingSetId: tastingSetId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#updateTastingSet, [], {
                  #tastingSetId: tastingSetId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.EnhancedOrder> createEnhancedOrderWithShipping({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? baseOrderValue,
    double? taxAmount = 0.0,
    String? currency = 'EUR',
    required _i14.DeliveryAddress? deliveryAddress,
    _i3.DeliveryType? deliveryType = _i3.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrderWithShipping, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #baseOrderValue: baseOrderValue,
              #taxAmount: taxAmount,
              #currency: currency,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i9.Future<_i5.EnhancedOrder>.value(
              _FakeEnhancedOrder_3(
                this,
                Invocation.method(#createEnhancedOrderWithShipping, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #baseOrderValue: baseOrderValue,
                  #taxAmount: taxAmount,
                  #currency: currency,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.EnhancedOrder>);

  @override
  _i9.Future<_i5.EnhancedOrder> createEnhancedOrder({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? subtotal,
    double? taxAmount = 0.0,
    double? shippingCost = 0.0,
    required double? totalAmount,
    String? currency = 'EUR',
    double? baseAmount = 0.0,
    required _i14.DeliveryAddress? deliveryAddress,
    _i3.DeliveryType? deliveryType = _i3.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrder, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #subtotal: subtotal,
              #taxAmount: taxAmount,
              #shippingCost: shippingCost,
              #totalAmount: totalAmount,
              #currency: currency,
              #baseAmount: baseAmount,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i9.Future<_i5.EnhancedOrder>.value(
              _FakeEnhancedOrder_3(
                this,
                Invocation.method(#createEnhancedOrder, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #subtotal: subtotal,
                  #taxAmount: taxAmount,
                  #shippingCost: shippingCost,
                  #totalAmount: totalAmount,
                  #currency: currency,
                  #baseAmount: baseAmount,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.EnhancedOrder>);

  @override
  _i9.Future<_i5.EnhancedOrder?> getEnhancedOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedOrderById, [orderId]),
            returnValue: _i9.Future<_i5.EnhancedOrder?>.value(),
          )
          as _i9.Future<_i5.EnhancedOrder?>);

  @override
  _i9.Future<List<_i5.EnhancedOrder>> getCustomerEnhancedOrders({
    required String? customerId,
    int? limit = 50,
    int? offset = 0,
    List<String>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerEnhancedOrders, [], {
              #customerId: customerId,
              #limit: limit,
              #offset: offset,
              #statuses: statuses,
            }),
            returnValue: _i9.Future<List<_i5.EnhancedOrder>>.value(
              <_i5.EnhancedOrder>[],
            ),
          )
          as _i9.Future<List<_i5.EnhancedOrder>>);

  @override
  _i9.Future<_i5.EnhancedOrder> updateEnhancedOrderStatus({
    required int? orderId,
    required String? newStatus,
    String? reason,
    String? notes,
    String? trackingNumber,
    String? trackingUrl,
    String? shippingCarrier,
    DateTime? estimatedDelivery,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEnhancedOrderStatus, [], {
              #orderId: orderId,
              #newStatus: newStatus,
              #reason: reason,
              #notes: notes,
              #trackingNumber: trackingNumber,
              #trackingUrl: trackingUrl,
              #shippingCarrier: shippingCarrier,
              #estimatedDelivery: estimatedDelivery,
              #metadata: metadata,
            }),
            returnValue: _i9.Future<_i5.EnhancedOrder>.value(
              _FakeEnhancedOrder_3(
                this,
                Invocation.method(#updateEnhancedOrderStatus, [], {
                  #orderId: orderId,
                  #newStatus: newStatus,
                  #reason: reason,
                  #notes: notes,
                  #trackingNumber: trackingNumber,
                  #trackingUrl: trackingUrl,
                  #shippingCarrier: shippingCarrier,
                  #estimatedDelivery: estimatedDelivery,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.EnhancedOrder>);

  @override
  _i9.Future<List<_i5.OrderStatusChange>> getOrderStatusHistory(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusHistory, [orderId]),
            returnValue: _i9.Future<List<_i5.OrderStatusChange>>.value(
              <_i5.OrderStatusChange>[],
            ),
          )
          as _i9.Future<List<_i5.OrderStatusChange>>);

  @override
  _i9.Future<_i5.EnhancedOrder> convertBasicToEnhancedOrder({
    required _i3.BasicOrder? basicOrder,
    required String? companyId,
    required _i14.DeliveryAddress? deliveryAddress,
    String? customerEmail,
    String? customerPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertBasicToEnhancedOrder, [], {
              #basicOrder: basicOrder,
              #companyId: companyId,
              #deliveryAddress: deliveryAddress,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
            }),
            returnValue: _i9.Future<_i5.EnhancedOrder>.value(
              _FakeEnhancedOrder_3(
                this,
                Invocation.method(#convertBasicToEnhancedOrder, [], {
                  #basicOrder: basicOrder,
                  #companyId: companyId,
                  #deliveryAddress: deliveryAddress,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.EnhancedOrder>);

  @override
  _i9.Future<List<_i6.Review>> getReviewsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForHike, [hikeId]),
            returnValue: _i9.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i9.Future<List<_i6.Review>>);

  @override
  _i9.Future<_i6.Review> createReview({
    required int? hikeId,
    required String? userId,
    required double? rating,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [], {
              #hikeId: hikeId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i9.Future<_i6.Review>.value(
              _FakeReview_4(
                this,
                Invocation.method(#createReview, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.Review>);

  @override
  _i9.Future<_i6.Review> updateReview({
    required int? reviewId,
    required String? userId,
    double? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [], {
              #reviewId: reviewId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i9.Future<_i6.Review>.value(
              _FakeReview_4(
                this,
                Invocation.method(#updateReview, [], {
                  #reviewId: reviewId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.Review>);

  @override
  _i9.Future<void> deleteReview({
    required int? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [], {
              #reviewId: reviewId,
              #userId: userId,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i6.Review>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByUser, [userId]),
            returnValue: _i9.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i9.Future<List<_i6.Review>>);

  @override
  _i9.Future<double> getAverageRatingForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getAverageRatingForHike, [hikeId]),
            returnValue: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<_i6.Review?> getUserReviewForHike({
    required int? hikeId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReviewForHike, [], {
              #hikeId: hikeId,
              #userId: userId,
            }),
            returnValue: _i9.Future<_i6.Review?>.value(),
          )
          as _i9.Future<_i6.Review?>);

  @override
  _i9.Future<Map<String, dynamic>> getReviewStatsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewStatsForHike, [hikeId]),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<List<_i6.Review>> getRecentReviews({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentReviews, [], {#limit: limit}),
            returnValue: _i9.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i9.Future<List<_i6.Review>>);
}
