// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i13;
import 'dart:ui' as _i16;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:shared_preferences/shared_preferences.dart' as _i28;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:whisky_hikes/data/repositories/hike_images_repository.dart'
    as _i17;
import 'package:whisky_hikes/data/repositories/offline_first_hike_repository.dart'
    as _i8;
import 'package:whisky_hikes/data/repositories/offline_first_waypoint_repository.dart'
    as _i18;
import 'package:whisky_hikes/data/repositories/profile_repository.dart' as _i11;
import 'package:whisky_hikes/data/repositories/tasting_set_repository.dart'
    as _i20;
import 'package:whisky_hikes/data/repositories/user_repository.dart' as _i15;
import 'package:whisky_hikes/data/services/auth/auth_service.dart' as _i21;
import 'package:whisky_hikes/data/services/cache/local_cache_service.dart'
    as _i23;
import 'package:whisky_hikes/data/services/connectivity/connectivity_service.dart'
    as _i22;
import 'package:whisky_hikes/data/services/database/backend_api.dart' as _i26;
import 'package:whisky_hikes/data/services/payment/multi_payment_service.dart'
    as _i24;
import 'package:whisky_hikes/domain/models/account.dart' as _i3;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i5;
import 'package:whisky_hikes/domain/models/delivery_address.dart' as _i27;
import 'package:whisky_hikes/domain/models/enhanced_order.dart' as _i6;
import 'package:whisky_hikes/domain/models/hike.dart' as _i10;
import 'package:whisky_hikes/domain/models/payment_intent.dart' as _i25;
import 'package:whisky_hikes/domain/models/profile.dart' as _i12;
import 'package:whisky_hikes/domain/models/review.dart' as _i7;
import 'package:whisky_hikes/domain/models/tasting_set.dart' as _i4;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_1 extends _i1.SmartFake implements _i3.Account {
  _FakeAccount_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTastingSet_2 extends _i1.SmartFake implements _i4.TastingSet {
  _FakeTastingSet_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWhiskySample_3 extends _i1.SmartFake implements _i4.WhiskySample {
  _FakeWhiskySample_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_4 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasicOrder_5 extends _i1.SmartFake implements _i5.BasicOrder {
  _FakeBasicOrder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnhancedOrder_6 extends _i1.SmartFake implements _i6.EnhancedOrder {
  _FakeEnhancedOrder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReview_7 extends _i1.SmartFake implements _i7.Review {
  _FakeReview_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_8 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_9 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_10 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_11 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_12 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_13 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_14 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_15<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_16 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OfflineFirstHikeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineFirstHikeRepository extends _i1.Mock
    implements _i8.OfflineFirstHikeRepository {
  MockOfflineFirstHikeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i10.Hike>> getAllAvailableHikes({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllAvailableHikes, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i9.Future<List<_i10.Hike>>.value(<_i10.Hike>[]),
          )
          as _i9.Future<List<_i10.Hike>>);

  @override
  _i9.Future<List<_i10.Hike>> getUserHikes(
    String? userId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserHikes,
              [userId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i9.Future<List<_i10.Hike>>.value(<_i10.Hike>[]),
          )
          as _i9.Future<List<_i10.Hike>>);

  @override
  _i9.Future<void> clearHikeCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearHikeCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i11.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i12.Profile?> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i9.Future<_i12.Profile?>.value(),
          )
          as _i9.Future<_i12.Profile?>);

  @override
  _i9.Future<void> updateUserProfile(_i12.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> uploadProfileImage(
    String? userId,
    _i13.Uint8List? imageBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              imageBytes,
              fileExt,
            ]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  imageBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> clearUserCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserCache, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<bool> hasNetworkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasNetworkConnection, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i15.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  set isLoggedIn(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoggedIn, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> signUserOut() =>
      (super.noSuchMethod(
            Invocation.method(#signUserOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.AuthResponse> signUpWithEmailPassword(
    String? email,
    String? password, [
    Map<String, dynamic>? data,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [
              email,
              password,
              data,
            ]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUpWithEmailPassword, [
                  email,
                  password,
                  data,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<_i2.AuthResponse> loginWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailAndPassword, [email, password]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#loginWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<void> sendMagicLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendMagicLink, [email]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.AuthResponse> verifyMagicLinkCode(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLinkCode, [email, code]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#verifyMagicLinkCode, [email, code]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  void signalAuthChanged() => super.noSuchMethod(
    Invocation.method(#signalAuthChanged, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<void> updateUserEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserEmail, [newEmail]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.Account> getAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, []),
            returnValue: _i9.Future<_i3.Account>.value(
              _FakeAccount_1(this, Invocation.method(#getAccount, [])),
            ),
          )
          as _i9.Future<_i3.Account>);

  @override
  _i9.Future<List<_i3.Account>> listAccounts({int? limit = 500}) =>
      (super.noSuchMethod(
            Invocation.method(#listAccounts, [], {#limit: limit}),
            returnValue: _i9.Future<List<_i3.Account>>.value(<_i3.Account>[]),
          )
          as _i9.Future<List<_i3.Account>>);

  @override
  _i9.Future<_i3.Account> setUserRole({
    required String? userId,
    required String? newRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserRole, [], {
              #userId: userId,
              #newRole: newRole,
            }),
            returnValue: _i9.Future<_i3.Account>.value(
              _FakeAccount_1(
                this,
                Invocation.method(#setUserRole, [], {
                  #userId: userId,
                  #newRole: newRole,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Account>);

  @override
  _i9.Future<bool> isCurrentUserAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#isCurrentUserAdmin, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HikeImagesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHikeImagesRepository extends _i1.Mock
    implements _i17.HikeImagesRepository {
  MockHikeImagesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> uploadHikeImages(
    _i10.Hike? hike,
    List<String>? imagePaths,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hike, imagePaths]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);
}

/// A class which mocks [OfflineFirstWaypointRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineFirstWaypointRepository extends _i1.Mock
    implements _i18.OfflineFirstWaypointRepository {
  MockOfflineFirstWaypointRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i19.Waypoint>> getWaypointsForHike(
    int? hikeId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWaypointsForHike,
              [hikeId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i9.Future<List<_i19.Waypoint>>.value(
              <_i19.Waypoint>[],
            ),
          )
          as _i9.Future<List<_i19.Waypoint>>);

  @override
  _i9.Future<void> clearWaypointCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearWaypointCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [TastingSetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTastingSetRepository extends _i1.Mock
    implements _i20.TastingSetRepository {
  MockTastingSetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i4.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<_i4.TastingSet?> getTastingSetByHikeId(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetByHikeId, [hikeId]),
            returnValue: _i9.Future<_i4.TastingSet?>.value(),
          )
          as _i9.Future<_i4.TastingSet?>);

  @override
  _i9.Future<_i4.TastingSet> createTastingSet(_i4.TastingSet? tastingSet) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [tastingSet]),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#createTastingSet, [tastingSet]),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<_i4.TastingSet> updateTastingSet(_i4.TastingSet? tastingSet) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [tastingSet]),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#updateTastingSet, [tastingSet]),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i4.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<List<_i4.WhiskySample>> getWhiskySamplesByTastingSetId(
    int? tastingSetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWhiskySamplesByTastingSetId, [tastingSetId]),
            returnValue: _i9.Future<List<_i4.WhiskySample>>.value(
              <_i4.WhiskySample>[],
            ),
          )
          as _i9.Future<List<_i4.WhiskySample>>);

  @override
  _i9.Future<_i4.WhiskySample> createWhiskySample(_i4.WhiskySample? sample) =>
      (super.noSuchMethod(
            Invocation.method(#createWhiskySample, [sample]),
            returnValue: _i9.Future<_i4.WhiskySample>.value(
              _FakeWhiskySample_3(
                this,
                Invocation.method(#createWhiskySample, [sample]),
              ),
            ),
          )
          as _i9.Future<_i4.WhiskySample>);

  @override
  _i9.Future<_i4.WhiskySample> updateWhiskySample(_i4.WhiskySample? sample) =>
      (super.noSuchMethod(
            Invocation.method(#updateWhiskySample, [sample]),
            returnValue: _i9.Future<_i4.WhiskySample>.value(
              _FakeWhiskySample_3(
                this,
                Invocation.method(#updateWhiskySample, [sample]),
              ),
            ),
          )
          as _i9.Future<_i4.WhiskySample>);

  @override
  _i9.Future<void> deleteWhiskySample(int? sampleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWhiskySample, [sampleId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateSampleOrder(
    List<_i4.WhiskySample>? reorderedSamples,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSampleOrder, [reorderedSamples]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> uploadWhiskyImage(
    int? sampleId,
    _i13.Uint8List? imageBytes,
    String? fileExtension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadWhiskyImage, [
              sampleId,
              imageBytes,
              fileExtension,
            ]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadWhiskyImage, [
                  sampleId,
                  imageBytes,
                  fileExtension,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String> uploadTastingSetImage(
    int? tastingSetId,
    _i13.Uint8List? imageBytes,
    String? fileExtension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadTastingSetImage, [
              tastingSetId,
              imageBytes,
              fileExtension,
            ]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadTastingSetImage, [
                  tastingSetId,
                  imageBytes,
                  fileExtension,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<Map<String, dynamic>> getTastingSetStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetStatistics, []),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getPopularDistilleries({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularDistilleries, [], {#limit: limit}),
            returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i21.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_4(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.SupabaseClient);

  @override
  bool get isDevMode =>
      (super.noSuchMethod(Invocation.getter(#isDevMode), returnValue: false)
          as bool);

  @override
  _i9.Future<_i2.AuthResponse> signInWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [email, password]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithEmailPassword, [email, password]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<_i2.AuthResponse> signUpWithEmailPassword(
    String? email,
    String? password, [
    Map<String, dynamic>? data,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [
              email,
              password,
              data,
            ]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUpWithEmailPassword, [
                  email,
                  password,
                  data,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  bool isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<bool> isCurrentUserAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#isCurrentUserAdmin, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> updateUserEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserEmail, [newEmail]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> confirmEmailManually() =>
      (super.noSuchMethod(
            Invocation.method(#confirmEmailManually, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendMagicLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendMagicLink, [email]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.AuthResponse> verifyMagicLinkCode(
    String? email,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLinkCode, [email, token]),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#verifyMagicLinkCode, [email, token]),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<void> handleEmailConfirmation(String? token, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#handleEmailConfirmation, [token, type]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i22.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.NetworkStatus get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i22.NetworkStatus.unknown,
          )
          as _i22.NetworkStatus);

  @override
  _i9.Stream<_i22.NetworkStatus> get networkStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#networkStatusStream),
            returnValue: _i9.Stream<_i22.NetworkStatus>.empty(),
          )
          as _i9.Stream<_i22.NetworkStatus>);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i22.NetworkStatus> checkNetworkStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkNetworkStatus, []),
            returnValue: _i9.Future<_i22.NetworkStatus>.value(
              _i22.NetworkStatus.unknown,
            ),
          )
          as _i9.Future<_i22.NetworkStatus>);

  @override
  _i9.Future<bool> hasInternetConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternetConnection, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> canReachHost(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#canReachHost, [host]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> canReachSupabase() =>
      (super.noSuchMethod(
            Invocation.method(#canReachSupabase, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  Map<String, dynamic> getNetworkStats() =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [LocalCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCacheService extends _i1.Mock implements _i23.LocalCacheService {
  MockLocalCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> cacheProfileData(_i12.Profile? profile, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProfileData, [profile, userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i12.Profile?> getCachedProfileData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfileData, [userId]),
            returnValue: _i9.Future<_i12.Profile?>.value(),
          )
          as _i9.Future<_i12.Profile?>);

  @override
  _i9.Future<String?> cacheProfileImage(
    String? userId,
    _i13.Uint8List? imageBytes,
    String? fileExtension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProfileImage, [
              userId,
              imageBytes,
              fileExtension,
            ]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> getCachedProfileImagePath(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfileImagePath, [userId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> hasValidProfileDataCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidProfileDataCache, [userId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> hasValidProfileImageCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidProfileImageCache, [userId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> clearProfileDataCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearProfileDataCache, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearProfileImageCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearProfileImageCache, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearUserCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserCache, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<bool> hasNetworkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasNetworkConnection, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [MultiPaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiPaymentService extends _i1.Mock
    implements _i24.MultiPaymentService {
  MockMultiPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isPaymentMethodAvailable(
    _i25.PaymentMethodType? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isPaymentMethodAvailable, [paymentMethod]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<List<_i25.PaymentMethodType>> getAvailablePaymentMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePaymentMethods, []),
            returnValue: _i9.Future<List<_i25.PaymentMethodType>>.value(
              <_i25.PaymentMethodType>[],
            ),
          )
          as _i9.Future<List<_i25.PaymentMethodType>>);

  @override
  String getPaymentMethodDisplayName(_i25.PaymentMethodType? paymentMethod) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentMethodDisplayName, [paymentMethod]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#getPaymentMethodDisplayName, [paymentMethod]),
            ),
          )
          as String);

  @override
  String getPaymentMethodIcon(_i25.PaymentMethodType? paymentMethod) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentMethodIcon, [paymentMethod]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#getPaymentMethodIcon, [paymentMethod]),
            ),
          )
          as String);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i26.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_4(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i9.Future<_i12.Profile?> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i9.Future<_i12.Profile?>.value(),
          )
          as _i9.Future<_i12.Profile?>);

  @override
  _i9.Future<List<_i10.Hike>> fetchHikes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHikes, []),
            returnValue: _i9.Future<List<_i10.Hike>>.value(<_i10.Hike>[]),
          )
          as _i9.Future<List<_i10.Hike>>);

  @override
  _i9.Future<List<_i10.Hike>> fetchUserHikes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserHikes, [userId]),
            returnValue: _i9.Future<List<_i10.Hike>>.value(<_i10.Hike>[]),
          )
          as _i9.Future<List<_i10.Hike>>);

  @override
  _i9.Future<void> deleteHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHike, [hikeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> uploadHikeImages(int? hikeId, List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hikeId, imageUrls]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserProfile(_i12.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> uploadProfileImage(
    String? userId,
    _i13.Uint8List? fileBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              fileBytes,
              fileExt,
            ]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  fileBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<List<_i19.Waypoint>> getWaypointsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getWaypointsForHike, [hikeId]),
            returnValue: _i9.Future<List<_i19.Waypoint>>.value(
              <_i19.Waypoint>[],
            ),
          )
          as _i9.Future<List<_i19.Waypoint>>);

  @override
  _i9.Future<void> addWaypoint(
    _i19.Waypoint? waypoint,
    int? hikeId, {
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addWaypoint,
              [waypoint, hikeId],
              {#orderIndex: orderIndex},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateWaypoint(_i19.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypoint, [waypoint]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateWaypointOrder(
    int? hikeId,
    int? waypointId,
    int? newOrderIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypointOrder, [
              hikeId,
              waypointId,
              newOrderIndex,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i5.BasicOrder>> fetchUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserOrders, [userId]),
            returnValue: _i9.Future<List<_i5.BasicOrder>>.value(
              <_i5.BasicOrder>[],
            ),
          )
          as _i9.Future<List<_i5.BasicOrder>>);

  @override
  _i9.Future<_i5.BasicOrder> fetchOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i9.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_5(
                this,
                Invocation.method(#fetchOrderById, [orderId]),
              ),
            ),
          )
          as _i9.Future<_i5.BasicOrder>);

  @override
  _i9.Future<bool> hasUserPurchasedHike(String? userId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserPurchasedHike, [userId, hikeId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> recordHikePurchase(
    String? userId,
    int? hikeId,
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordHikePurchase, [userId, hikeId, orderId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.BasicOrder> fetchOrderWithPaymentDetails(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
            returnValue: _i9.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_5(
                this,
                Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
              ),
            ),
          )
          as _i9.Future<_i5.BasicOrder>);

  @override
  _i9.Future<_i5.BasicOrder> updateOrderAfterPayment({
    required int? orderId,
    required _i5.OrderStatus? status,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderAfterPayment, [], {
              #orderId: orderId,
              #status: status,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i9.Future<_i5.BasicOrder>.value(
              _FakeBasicOrder_5(
                this,
                Invocation.method(#updateOrderAfterPayment, [], {
                  #orderId: orderId,
                  #status: status,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.BasicOrder>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getUserPaymentHistory(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPaymentHistory, [userId]),
            returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<List<_i4.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<List<_i4.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i9.Future<List<_i4.TastingSet>>.value(
              <_i4.TastingSet>[],
            ),
          )
          as _i9.Future<List<_i4.TastingSet>>);

  @override
  _i9.Future<_i4.TastingSet> createTastingSet({
    required int? hikeId,
    required String? name,
    required String? description,
    String? imageUrl,
    bool? isIncluded = true,
    bool? isAvailable = true,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [], {
              #hikeId: hikeId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#createTastingSet, [], {
                  #hikeId: hikeId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<_i4.TastingSet> updateTastingSet({
    required int? tastingSetId,
    String? name,
    String? description,
    String? imageUrl,
    bool? isIncluded,
    bool? isAvailable,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [], {
              #tastingSetId: tastingSetId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i9.Future<_i4.TastingSet>.value(
              _FakeTastingSet_2(
                this,
                Invocation.method(#updateTastingSet, [], {
                  #tastingSetId: tastingSetId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.TastingSet>);

  @override
  _i9.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.EnhancedOrder> createEnhancedOrderWithShipping({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? baseOrderValue,
    double? taxAmount = 0.0,
    String? currency = 'EUR',
    required _i27.DeliveryAddress? deliveryAddress,
    _i5.DeliveryType? deliveryType = _i5.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrderWithShipping, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #baseOrderValue: baseOrderValue,
              #taxAmount: taxAmount,
              #currency: currency,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i9.Future<_i6.EnhancedOrder>.value(
              _FakeEnhancedOrder_6(
                this,
                Invocation.method(#createEnhancedOrderWithShipping, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #baseOrderValue: baseOrderValue,
                  #taxAmount: taxAmount,
                  #currency: currency,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.EnhancedOrder>);

  @override
  _i9.Future<_i6.EnhancedOrder> createEnhancedOrder({
    required String? orderNumber,
    required String? companyId,
    required String? customerId,
    int? hikeId,
    required double? subtotal,
    double? taxAmount = 0.0,
    double? shippingCost = 0.0,
    required double? totalAmount,
    String? currency = 'EUR',
    double? baseAmount = 0.0,
    required _i27.DeliveryAddress? deliveryAddress,
    _i5.DeliveryType? deliveryType = _i5.DeliveryType.standardShipping,
    String? customerEmail,
    String? customerPhone,
    String? notes,
    Map<String, dynamic>? metadata,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnhancedOrder, [], {
              #orderNumber: orderNumber,
              #companyId: companyId,
              #customerId: customerId,
              #hikeId: hikeId,
              #subtotal: subtotal,
              #taxAmount: taxAmount,
              #shippingCost: shippingCost,
              #totalAmount: totalAmount,
              #currency: currency,
              #baseAmount: baseAmount,
              #deliveryAddress: deliveryAddress,
              #deliveryType: deliveryType,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
              #notes: notes,
              #metadata: metadata,
              #tags: tags,
            }),
            returnValue: _i9.Future<_i6.EnhancedOrder>.value(
              _FakeEnhancedOrder_6(
                this,
                Invocation.method(#createEnhancedOrder, [], {
                  #orderNumber: orderNumber,
                  #companyId: companyId,
                  #customerId: customerId,
                  #hikeId: hikeId,
                  #subtotal: subtotal,
                  #taxAmount: taxAmount,
                  #shippingCost: shippingCost,
                  #totalAmount: totalAmount,
                  #currency: currency,
                  #baseAmount: baseAmount,
                  #deliveryAddress: deliveryAddress,
                  #deliveryType: deliveryType,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                  #notes: notes,
                  #metadata: metadata,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.EnhancedOrder>);

  @override
  _i9.Future<_i6.EnhancedOrder?> getEnhancedOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedOrderById, [orderId]),
            returnValue: _i9.Future<_i6.EnhancedOrder?>.value(),
          )
          as _i9.Future<_i6.EnhancedOrder?>);

  @override
  _i9.Future<List<_i6.EnhancedOrder>> getCustomerEnhancedOrders({
    required String? customerId,
    int? limit = 50,
    int? offset = 0,
    List<String>? statuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerEnhancedOrders, [], {
              #customerId: customerId,
              #limit: limit,
              #offset: offset,
              #statuses: statuses,
            }),
            returnValue: _i9.Future<List<_i6.EnhancedOrder>>.value(
              <_i6.EnhancedOrder>[],
            ),
          )
          as _i9.Future<List<_i6.EnhancedOrder>>);

  @override
  _i9.Future<_i6.EnhancedOrder> updateEnhancedOrderStatus({
    required int? orderId,
    required String? newStatus,
    String? reason,
    String? notes,
    String? trackingNumber,
    String? trackingUrl,
    String? shippingCarrier,
    DateTime? estimatedDelivery,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEnhancedOrderStatus, [], {
              #orderId: orderId,
              #newStatus: newStatus,
              #reason: reason,
              #notes: notes,
              #trackingNumber: trackingNumber,
              #trackingUrl: trackingUrl,
              #shippingCarrier: shippingCarrier,
              #estimatedDelivery: estimatedDelivery,
              #metadata: metadata,
            }),
            returnValue: _i9.Future<_i6.EnhancedOrder>.value(
              _FakeEnhancedOrder_6(
                this,
                Invocation.method(#updateEnhancedOrderStatus, [], {
                  #orderId: orderId,
                  #newStatus: newStatus,
                  #reason: reason,
                  #notes: notes,
                  #trackingNumber: trackingNumber,
                  #trackingUrl: trackingUrl,
                  #shippingCarrier: shippingCarrier,
                  #estimatedDelivery: estimatedDelivery,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.EnhancedOrder>);

  @override
  _i9.Future<List<_i6.OrderStatusChange>> getOrderStatusHistory(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusHistory, [orderId]),
            returnValue: _i9.Future<List<_i6.OrderStatusChange>>.value(
              <_i6.OrderStatusChange>[],
            ),
          )
          as _i9.Future<List<_i6.OrderStatusChange>>);

  @override
  _i9.Future<_i6.EnhancedOrder> convertBasicToEnhancedOrder({
    required _i5.BasicOrder? basicOrder,
    required String? companyId,
    required _i27.DeliveryAddress? deliveryAddress,
    String? customerEmail,
    String? customerPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertBasicToEnhancedOrder, [], {
              #basicOrder: basicOrder,
              #companyId: companyId,
              #deliveryAddress: deliveryAddress,
              #customerEmail: customerEmail,
              #customerPhone: customerPhone,
            }),
            returnValue: _i9.Future<_i6.EnhancedOrder>.value(
              _FakeEnhancedOrder_6(
                this,
                Invocation.method(#convertBasicToEnhancedOrder, [], {
                  #basicOrder: basicOrder,
                  #companyId: companyId,
                  #deliveryAddress: deliveryAddress,
                  #customerEmail: customerEmail,
                  #customerPhone: customerPhone,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.EnhancedOrder>);

  @override
  _i9.Future<List<_i7.Review>> getReviewsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForHike, [hikeId]),
            returnValue: _i9.Future<List<_i7.Review>>.value(<_i7.Review>[]),
          )
          as _i9.Future<List<_i7.Review>>);

  @override
  _i9.Future<_i7.Review> createReview({
    required int? hikeId,
    required String? userId,
    required double? rating,
    required String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [], {
              #hikeId: hikeId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i9.Future<_i7.Review>.value(
              _FakeReview_7(
                this,
                Invocation.method(#createReview, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.Review>);

  @override
  _i9.Future<_i7.Review> updateReview({
    required int? reviewId,
    required String? userId,
    double? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [], {
              #reviewId: reviewId,
              #userId: userId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i9.Future<_i7.Review>.value(
              _FakeReview_7(
                this,
                Invocation.method(#updateReview, [], {
                  #reviewId: reviewId,
                  #userId: userId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.Review>);

  @override
  _i9.Future<void> deleteReview({
    required int? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [], {
              #reviewId: reviewId,
              #userId: userId,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i7.Review>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByUser, [userId]),
            returnValue: _i9.Future<List<_i7.Review>>.value(<_i7.Review>[]),
          )
          as _i9.Future<List<_i7.Review>>);

  @override
  _i9.Future<double> getAverageRatingForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getAverageRatingForHike, [hikeId]),
            returnValue: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<_i7.Review?> getUserReviewForHike({
    required int? hikeId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReviewForHike, [], {
              #hikeId: hikeId,
              #userId: userId,
            }),
            returnValue: _i9.Future<_i7.Review?>.value(),
          )
          as _i9.Future<_i7.Review?>);

  @override
  _i9.Future<Map<String, dynamic>> getReviewStatsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewStatsForHike, [hikeId]),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<List<_i7.Review>> getRecentReviews({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentReviews, [], {#limit: limit}),
            returnValue: _i9.Future<List<_i7.Review>>.value(<_i7.Review>[]),
          )
          as _i9.Future<List<_i7.Review>>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_8(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_9(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_10(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_11(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i2.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_12(this, Invocation.getter(#auth)),
          )
          as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? newHeaders) => super.noSuchMethod(
    Invocation.setter(#headers, newHeaders),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_13(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_14(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_15<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_16(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i9.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i28.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i9.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
