// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i14;

import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i21;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;
import 'package:whisky_hikes/data/models/pagination_result.dart' as _i2;
import 'package:whisky_hikes/data/repositories/hike_images_repository.dart'
    as _i15;
import 'package:whisky_hikes/data/repositories/hike_repository.dart' as _i7;
import 'package:whisky_hikes/data/repositories/profile_repository.dart' as _i10;
import 'package:whisky_hikes/data/repositories/tasting_set_repository.dart'
    as _i18;
import 'package:whisky_hikes/data/repositories/user_repository.dart' as _i13;
import 'package:whisky_hikes/data/repositories/waypoint_repository.dart'
    as _i16;
import 'package:whisky_hikes/data/services/auth/auth_service.dart' as _i19;
import 'package:whisky_hikes/data/services/cache/local_cache_service.dart'
    as _i20;
import 'package:whisky_hikes/domain/models/hike.dart' as _i9;
import 'package:whisky_hikes/domain/models/profile.dart' as _i3;
import 'package:whisky_hikes/domain/models/tasting_set.dart' as _i6;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginationResult_0<T> extends _i1.SmartFake
    implements _i2.PaginationResult<T> {
  _FakePaginationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeAuthResponse_2 extends _i1.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTastingSet_3 extends _i1.SmartFake implements _i6.TastingSet {
  _FakeTastingSet_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_4 extends _i1.SmartFake
    implements _i5.SupabaseClient {
  _FakeSupabaseClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HikeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHikeRepository extends _i1.Mock implements _i7.HikeRepository {
  MockHikeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i9.Hike>> getAllAvailableHikes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAvailableHikes, []),
            returnValue: _i8.Future<List<_i9.Hike>>.value(<_i9.Hike>[]),
          )
          as _i8.Future<List<_i9.Hike>>);

  @override
  _i8.Future<_i2.PaginationResult<_i9.Hike>> getHikesPaginated(
    _i2.PaginationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHikesPaginated, [params]),
            returnValue: _i8.Future<_i2.PaginationResult<_i9.Hike>>.value(
              _FakePaginationResult_0<_i9.Hike>(
                this,
                Invocation.method(#getHikesPaginated, [params]),
              ),
            ),
          )
          as _i8.Future<_i2.PaginationResult<_i9.Hike>>);

  @override
  _i8.Future<List<_i9.Hike>> getUserHikes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserHikes, [userId]),
            returnValue: _i8.Future<List<_i9.Hike>>.value(<_i9.Hike>[]),
          )
          as _i8.Future<List<_i9.Hike>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i10.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Profile> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i8.Future<_i3.Profile>.value(
              _FakeProfile_1(
                this,
                Invocation.method(#getUserProfileById, [id]),
              ),
            ),
          )
          as _i8.Future<_i3.Profile>);

  @override
  _i8.Future<void> updateUserProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> uploadProfileImage(
    String? userId,
    _i11.Uint8List? imageBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              imageBytes,
              fileExt,
            ]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  imageBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> clearUserCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserCache, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> hasNetworkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasNetworkConnection, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i13.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  set isLoggedIn(bool? _isLoggedIn) => super.noSuchMethod(
    Invocation.setter(#isLoggedIn, _isLoggedIn),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> signUserOut() =>
      (super.noSuchMethod(
            Invocation.method(#signUserOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.AuthResponse> signUpWithEmailPassword(
    String? email,
    String? password, [
    Map<String, dynamic>? data,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [
              email,
              password,
              data,
            ]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signUpWithEmailPassword, [
                  email,
                  password,
                  data,
                ]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.AuthResponse> loginWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailAndPassword, [email, password]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#loginWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  bool isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> updateUserEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserEmail, [newEmail]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HikeImagesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHikeImagesRepository extends _i1.Mock
    implements _i15.HikeImagesRepository {
  MockHikeImagesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> uploadHikeImages(_i9.Hike? hike, List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hike, imagePaths]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);
}

/// A class which mocks [WaypointRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWaypointRepository extends _i1.Mock
    implements _i16.WaypointRepository {
  MockWaypointRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i17.Waypoint>> getWaypointsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getWaypointsForHike, [hikeId]),
            returnValue: _i8.Future<List<_i17.Waypoint>>.value(
              <_i17.Waypoint>[],
            ),
          )
          as _i8.Future<List<_i17.Waypoint>>);

  @override
  _i8.Future<void> addWaypoint(
    _i17.Waypoint? waypoint,
    int? hikeId, {
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addWaypoint,
              [waypoint, hikeId],
              {#orderIndex: orderIndex},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateWaypoint(_i17.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypoint, [waypoint]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteWaypoint(int? waypointId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWaypoint, [waypointId, hikeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateWaypointOrder(
    int? hikeId,
    int? waypointId,
    int? newOrderIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypointOrder, [
              hikeId,
              waypointId,
              newOrderIndex,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [TastingSetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTastingSetRepository extends _i1.Mock
    implements _i18.TastingSetRepository {
  MockTastingSetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.TastingSet?> getTastingSetForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetForHike, [hikeId]),
            returnValue: _i8.Future<_i6.TastingSet?>.value(),
          )
          as _i8.Future<_i6.TastingSet?>);

  @override
  _i8.Future<_i6.TastingSet?> getTastingSetById(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetById, [tastingSetId]),
            returnValue: _i8.Future<_i6.TastingSet?>.value(),
          )
          as _i8.Future<_i6.TastingSet?>);

  @override
  _i8.Future<List<_i6.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i8.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i6.TastingSet>>);

  @override
  _i8.Future<List<_i6.WhiskySample>> getWhiskySamplesForTastingSet(
    int? tastingSetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWhiskySamplesForTastingSet, [tastingSetId]),
            returnValue: _i8.Future<List<_i6.WhiskySample>>.value(
              <_i6.WhiskySample>[],
            ),
          )
          as _i8.Future<List<_i6.WhiskySample>>);

  @override
  _i8.Future<List<_i6.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i8.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i6.TastingSet>>);

  @override
  _i8.Future<List<_i6.TastingSet>> getTastingSetsByRegion(String? region) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsByRegion, [region]),
            returnValue: _i8.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i6.TastingSet>>);

  @override
  _i8.Future<List<_i6.TastingSet>> getCurrentlyAvailableTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentlyAvailableTastingSets, []),
            returnValue: _i8.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i6.TastingSet>>);

  @override
  _i8.Future<void> updateTastingSetAvailability({
    required int? tastingSetId,
    required bool? isAvailable,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSetAvailability, [], {
              #tastingSetId: tastingSetId,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.TastingSet>> getTastingSetsWithPagination({
    required int? page,
    required int? pageSize,
    String? searchQuery,
    String? region,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsWithPagination, [], {
              #page: page,
              #pageSize: pageSize,
              #searchQuery: searchQuery,
              #region: region,
            }),
            returnValue: _i8.Future<List<_i6.TastingSet>>.value(
              <_i6.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i6.TastingSet>>);

  @override
  _i8.Future<_i6.TastingSet> createTastingSet({
    required int? hikeId,
    required String? name,
    required String? description,
    String? imageUrl,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [], {
              #hikeId: hikeId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i8.Future<_i6.TastingSet>.value(
              _FakeTastingSet_3(
                this,
                Invocation.method(#createTastingSet, [], {
                  #hikeId: hikeId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.TastingSet>);

  @override
  _i8.Future<_i6.TastingSet> updateTastingSet({
    required int? tastingSetId,
    String? name,
    String? description,
    String? imageUrl,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [], {
              #tastingSetId: tastingSetId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i8.Future<_i6.TastingSet>.value(
              _FakeTastingSet_3(
                this,
                Invocation.method(#updateTastingSet, [], {
                  #tastingSetId: tastingSetId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.TastingSet>);

  @override
  _i8.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i19.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_4(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i5.SupabaseClient);

  @override
  bool get isDevMode =>
      (super.noSuchMethod(Invocation.getter(#isDevMode), returnValue: false)
          as bool);

  @override
  _i8.Future<_i5.AuthResponse> signInWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [email, password]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signInWithEmailPassword, [email, password]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.AuthResponse> signUpWithEmailPassword(
    String? email,
    String? password, [
    Map<String, dynamic>? data,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [
              email,
              password,
              data,
            ]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signUpWithEmailPassword, [
                  email,
                  password,
                  data,
                ]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> updateUserEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserEmail, [newEmail]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> confirmEmailManually() =>
      (super.noSuchMethod(
            Invocation.method(#confirmEmailManually, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> handleEmailConfirmation(String? token, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#handleEmailConfirmation, [token, type]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [LocalCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCacheService extends _i1.Mock implements _i20.LocalCacheService {
  MockLocalCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> cacheProfileData(_i3.Profile? profile, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProfileData, [profile, userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.Profile?> getCachedProfileData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfileData, [userId]),
            returnValue: _i8.Future<_i3.Profile?>.value(),
          )
          as _i8.Future<_i3.Profile?>);

  @override
  _i8.Future<String?> cacheProfileImage(
    String? userId,
    _i11.Uint8List? imageBytes,
    String? fileExtension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProfileImage, [
              userId,
              imageBytes,
              fileExtension,
            ]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getCachedProfileImagePath(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfileImagePath, [userId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<bool> hasValidProfileDataCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidProfileDataCache, [userId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> hasValidProfileImageCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidProfileImageCache, [userId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> clearProfileDataCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearProfileDataCache, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearProfileImageCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearProfileImageCache, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearUserCache(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserCache, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> hasNetworkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasNetworkConnection, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i21.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i8.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
