// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/UI/mobile/home/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:whisky_hikes/domain/models/hike.dart' as _i3;
import 'package:whisky_hikes/UI/mobile/home/home_view_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomePageViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomePageViewModel extends _i1.Mock implements _i2.HomePageViewModel {
  MockHomePageViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Hike> get hikes =>
      (super.noSuchMethod(Invocation.getter(#hikes), returnValue: <_i3.Hike>[])
          as List<_i3.Hike>);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  bool get showFavorites =>
      (super.noSuchMethod(Invocation.getter(#showFavorites), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadHikes({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadHikes, [], {#forceRefresh: forceRefresh}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> getUserFirstName() =>
      (super.noSuchMethod(
            Invocation.method(#getUserFirstName, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void toggleFavorite(_i3.Hike? hike) => super.noSuchMethod(
    Invocation.method(#toggleFavorite, [hike]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleShowFavorites() => super.noSuchMethod(
    Invocation.method(#toggleShowFavorites, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
