// Mocks generated by Mockito 5.4.6 from annotations
// in whisky_hikes/test/integration/order_tracking_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i12;

import 'package:flutter/src/foundation/diagnostics.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:supabase_flutter/supabase_flutter.dart' as _i4;
import 'package:whisky_hikes/data/repositories/payment_repository.dart' as _i7;
import 'package:whisky_hikes/data/services/database/backend_api.dart' as _i10;
import 'package:whisky_hikes/domain/models/basic_order.dart' as _i2;
import 'package:whisky_hikes/domain/models/basic_payment_result.dart' as _i3;
import 'package:whisky_hikes/domain/models/hike.dart' as _i11;
import 'package:whisky_hikes/domain/models/payment_intent.dart' as _i9;
import 'package:whisky_hikes/domain/models/profile.dart' as _i5;
import 'package:whisky_hikes/domain/models/tasting_set.dart' as _i15;
import 'package:whisky_hikes/domain/models/waypoint.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBasicOrder_0 extends _i1.SmartFake implements _i2.BasicOrder {
  _FakeBasicOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasicPaymentResult_1 extends _i1.SmartFake
    implements _i3.BasicPaymentResult {
  _FakeBasicPaymentResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_2 extends _i1.SmartFake
    implements _i4.SupabaseClient {
  _FakeSupabaseClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_3 extends _i1.SmartFake implements _i5.Profile {
  _FakeProfile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i7.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.BasicOrder> createOrder({
    required int? hikeId,
    required String? userId,
    required double? amount,
    required _i2.DeliveryType? deliveryType,
    Map<String, dynamic>? deliveryAddress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #hikeId: hikeId,
              #userId: userId,
              #amount: amount,
              #deliveryType: deliveryType,
              #deliveryAddress: deliveryAddress,
            }),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #hikeId: hikeId,
                  #userId: userId,
                  #amount: amount,
                  #deliveryType: deliveryType,
                  #deliveryAddress: deliveryAddress,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);

  @override
  _i8.Future<List<_i9.PaymentMethodType>> getAvailablePaymentMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePaymentMethods, []),
            returnValue: _i8.Future<List<_i9.PaymentMethodType>>.value(
              <_i9.PaymentMethodType>[],
            ),
          )
          as _i8.Future<List<_i9.PaymentMethodType>>);

  @override
  _i8.Future<bool> isPaymentMethodAvailable(
    _i9.PaymentMethodType? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isPaymentMethodAvailable, [paymentMethod]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.BasicPaymentResult> processPayment({
    required _i2.BasicOrder? order,
    required _i9.PaymentMethodType? paymentMethod,
    String? paymentMethodId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [], {
              #order: order,
              #paymentMethod: paymentMethod,
              #paymentMethodId: paymentMethodId,
              #metadata: metadata,
            }),
            returnValue: _i8.Future<_i3.BasicPaymentResult>.value(
              _FakeBasicPaymentResult_1(
                this,
                Invocation.method(#processPayment, [], {
                  #order: order,
                  #paymentMethod: paymentMethod,
                  #paymentMethodId: paymentMethodId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.BasicPaymentResult>);

  @override
  _i8.Future<_i3.BasicPaymentResult> processStripePayment({
    required _i2.BasicOrder? order,
    required String? paymentMethodId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processStripePayment, [], {
              #order: order,
              #paymentMethodId: paymentMethodId,
              #metadata: metadata,
            }),
            returnValue: _i8.Future<_i3.BasicPaymentResult>.value(
              _FakeBasicPaymentResult_1(
                this,
                Invocation.method(#processStripePayment, [], {
                  #order: order,
                  #paymentMethodId: paymentMethodId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.BasicPaymentResult>);

  @override
  _i8.Future<_i2.BasicOrder> getOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#getOrderById, [orderId]),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);

  @override
  _i8.Future<List<_i2.BasicOrder>> getUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [userId]),
            returnValue: _i8.Future<List<_i2.BasicOrder>>.value(
              <_i2.BasicOrder>[],
            ),
          )
          as _i8.Future<List<_i2.BasicOrder>>);

  @override
  _i8.Future<_i2.BasicOrder> updateOrderStatus({
    required int? orderId,
    required _i2.OrderStatus? status,
    String? trackingNumber,
    DateTime? estimatedDelivery,
    String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [], {
              #orderId: orderId,
              #status: status,
              #trackingNumber: trackingNumber,
              #estimatedDelivery: estimatedDelivery,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#updateOrderStatus, [], {
                  #orderId: orderId,
                  #status: status,
                  #trackingNumber: trackingNumber,
                  #estimatedDelivery: estimatedDelivery,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i10.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_2(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i4.SupabaseClient);

  @override
  _i8.Future<_i5.Profile> getUserProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileById, [id]),
            returnValue: _i8.Future<_i5.Profile>.value(
              _FakeProfile_3(
                this,
                Invocation.method(#getUserProfileById, [id]),
              ),
            ),
          )
          as _i8.Future<_i5.Profile>);

  @override
  _i8.Future<List<_i11.Hike>> fetchHikes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHikes, []),
            returnValue: _i8.Future<List<_i11.Hike>>.value(<_i11.Hike>[]),
          )
          as _i8.Future<List<_i11.Hike>>);

  @override
  _i8.Future<List<_i11.Hike>> fetchUserHikes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserHikes, [userId]),
            returnValue: _i8.Future<List<_i11.Hike>>.value(<_i11.Hike>[]),
          )
          as _i8.Future<List<_i11.Hike>>);

  @override
  _i8.Future<List<String>> getHikeImages(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getHikeImages, [hikeId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> uploadHikeImages(int? hikeId, List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHikeImages, [hikeId, imageUrls]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserProfile(_i5.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> uploadProfileImage(
    String? userId,
    _i12.Uint8List? fileBytes,
    String? fileExt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [
              userId,
              fileBytes,
              fileExt,
            ]),
            returnValue: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [
                  userId,
                  fileBytes,
                  fileExt,
                ]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> getProfileImageUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileImageUrl, [userId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<List<_i14.Waypoint>> getWaypointsForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getWaypointsForHike, [hikeId]),
            returnValue: _i8.Future<List<_i14.Waypoint>>.value(
              <_i14.Waypoint>[],
            ),
          )
          as _i8.Future<List<_i14.Waypoint>>);

  @override
  _i8.Future<void> addWaypoint(
    _i14.Waypoint? waypoint,
    int? hikeId, {
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addWaypoint,
              [waypoint, hikeId],
              {#orderIndex: orderIndex},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateWaypoint(_i14.Waypoint? waypoint) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypoint, [waypoint]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteWaypoint(int? waypointId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWaypoint, [waypointId, hikeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateWaypointOrder(
    int? hikeId,
    int? waypointId,
    int? newOrderIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaypointOrder, [
              hikeId,
              waypointId,
              newOrderIndex,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.BasicOrder>> fetchUserOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserOrders, [userId]),
            returnValue: _i8.Future<List<_i2.BasicOrder>>.value(
              <_i2.BasicOrder>[],
            ),
          )
          as _i8.Future<List<_i2.BasicOrder>>);

  @override
  _i8.Future<_i2.BasicOrder> fetchOrderById(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#fetchOrderById, [orderId]),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);

  @override
  _i8.Future<bool> hasUserPurchasedHike(String? userId, int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserPurchasedHike, [userId, hikeId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> recordHikePurchase(
    String? userId,
    int? hikeId,
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordHikePurchase, [userId, hikeId, orderId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.BasicOrder> fetchOrderWithPaymentDetails(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#fetchOrderWithPaymentDetails, [orderId]),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);

  @override
  _i8.Future<_i2.BasicOrder> updateOrderAfterPayment({
    required int? orderId,
    required _i2.OrderStatus? status,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderAfterPayment, [], {
              #orderId: orderId,
              #status: status,
              #paymentIntentId: paymentIntentId,
            }),
            returnValue: _i8.Future<_i2.BasicOrder>.value(
              _FakeBasicOrder_0(
                this,
                Invocation.method(#updateOrderAfterPayment, [], {
                  #orderId: orderId,
                  #status: status,
                  #paymentIntentId: paymentIntentId,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.BasicOrder>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getUserPaymentHistory(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPaymentHistory, [userId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i15.TastingSet?> getTastingSetForHike(int? hikeId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetForHike, [hikeId]),
            returnValue: _i8.Future<_i15.TastingSet?>.value(),
          )
          as _i8.Future<_i15.TastingSet?>);

  @override
  _i8.Future<_i15.TastingSet?> getTastingSetById(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetById, [tastingSetId]),
            returnValue: _i8.Future<_i15.TastingSet?>.value(),
          )
          as _i8.Future<_i15.TastingSet?>);

  @override
  _i8.Future<List<_i15.TastingSet>> getAllTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTastingSets, []),
            returnValue: _i8.Future<List<_i15.TastingSet>>.value(
              <_i15.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i15.TastingSet>>);

  @override
  _i8.Future<List<_i15.WhiskySample>> getWhiskySamplesForTastingSet(
    int? tastingSetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWhiskySamplesForTastingSet, [tastingSetId]),
            returnValue: _i8.Future<List<_i15.WhiskySample>>.value(
              <_i15.WhiskySample>[],
            ),
          )
          as _i8.Future<List<_i15.WhiskySample>>);

  @override
  _i8.Future<List<_i15.TastingSet>> searchTastingSets(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTastingSets, [query]),
            returnValue: _i8.Future<List<_i15.TastingSet>>.value(
              <_i15.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i15.TastingSet>>);

  @override
  _i8.Future<List<_i15.TastingSet>> getTastingSetsByRegion(String? region) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsByRegion, [region]),
            returnValue: _i8.Future<List<_i15.TastingSet>>.value(
              <_i15.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i15.TastingSet>>);

  @override
  _i8.Future<List<_i15.TastingSet>> getCurrentlyAvailableTastingSets() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentlyAvailableTastingSets, []),
            returnValue: _i8.Future<List<_i15.TastingSet>>.value(
              <_i15.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i15.TastingSet>>);

  @override
  _i8.Future<void> updateTastingSetAvailability(
    int? tastingSetId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSetAvailability, [
              tastingSetId,
              isAvailable,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i15.TastingSet>> getTastingSetsWithPagination({
    int? limit = 10,
    int? offset = 0,
    String? orderBy = 'created_at',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTastingSetsWithPagination, [], {
              #limit: limit,
              #offset: offset,
              #orderBy: orderBy,
              #ascending: ascending,
            }),
            returnValue: _i8.Future<List<_i15.TastingSet>>.value(
              <_i15.TastingSet>[],
            ),
          )
          as _i8.Future<List<_i15.TastingSet>>);

  @override
  _i8.Future<_i15.TastingSet> createTastingSet({
    required int? hikeId,
    required String? name,
    required String? description,
    String? imageUrl,
    bool? isIncluded = true,
    bool? isAvailable = true,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTastingSet, [], {
              #hikeId: hikeId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i8.Future<_i15.TastingSet>.value(
              _i13.dummyValue<_i15.TastingSet>(
                this,
                Invocation.method(#createTastingSet, [], {
                  #hikeId: hikeId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i8.Future<_i15.TastingSet>);

  @override
  _i8.Future<_i15.TastingSet> updateTastingSet({
    required int? tastingSetId,
    String? name,
    String? description,
    String? imageUrl,
    bool? isIncluded,
    bool? isAvailable,
    DateTime? availableFrom,
    DateTime? availableUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTastingSet, [], {
              #tastingSetId: tastingSetId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #isIncluded: isIncluded,
              #isAvailable: isAvailable,
              #availableFrom: availableFrom,
              #availableUntil: availableUntil,
            }),
            returnValue: _i8.Future<_i15.TastingSet>.value(
              _i13.dummyValue<_i15.TastingSet>(
                this,
                Invocation.method(#updateTastingSet, [], {
                  #tastingSetId: tastingSetId,
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #isIncluded: isIncluded,
                  #isAvailable: isAvailable,
                  #availableFrom: availableFrom,
                  #availableUntil: availableUntil,
                }),
              ),
            ),
          )
          as _i8.Future<_i15.TastingSet>);

  @override
  _i8.Future<void> deleteTastingSet(int? tastingSetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTastingSet, [tastingSetId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
